import test from "node:test";
import assert from "node:assert/strict";
import { ATTENTION, VISIBILITY, emptyDatabase, putEntity, removeEntity, arcDates, expandedSessionMembers, inheritedMembers, isPublic, publicationImpact, linkSynopsis, deriveAttention, historicalSuggestions, search, validateDatabase } from "../scripts/core.js";

const add = (db,type,name,fields={}) => putEntity(db,{type,name,...fields});
function fixture(){const db=emptyDatabase("test-world");const meta=add(db,"arc","Secret War",{arcType:"metaplot",status:"in-progress"});const arc=add(db,"arc","The Crow",{arcType:"arc",status:"in-progress",metaplotId:meta.id});const city=add(db,"area","Delta City",{areaType:"city",description:"City"});const district=add(db,"area","Racine",{areaType:"district",parentAreaId:city.id,description:"District"});const team=add(db,"affiliation","Golden Agents",{description:"Heroes"});const actor=add(db,"actor","Raven",{classification:"hero",description:"Detective",affiliationIds:[team.id],aliases:["The Raven"]});const scene=add(db,"scene","Il Padrino's",{description:"Restaurant",areaId:district.id});const session=add(db,"session","The Stakeout",{arcId:arc.id,playDate:"2026-08-29",synopsis:"Raven watched Raven from Il Padrino's.",memberIds:[actor.id,scene.id]});return{db,meta,arc,city,district,team,actor,scene,session};}

test("Session membership derives geography and affiliations",()=>{const {db,session,city,district,team}=fixture();const ids=expandedSessionMembers(db,session);assert.ok(ids.includes(city.id));assert.ok(ids.includes(district.id));assert.ok(ids.includes(team.id));});
test("Arc and Metaplot collections inherit Session content",()=>{const {db,arc,meta,actor}=fixture();assert.ok(inheritedMembers(db,arc).includes(actor.id));assert.ok(inheritedMembers(db,meta).includes(actor.id));});
test("Arc dates derive from Sessions",()=>{const {db,arc}=fixture();add(db,"session","Earlier",{arcId:arc.id,playDate:"2026-01-02",memberIds:[]});assert.deepEqual(arcDates(db,arc),{start:"2026-01-02",end:"2026-08-29"});});
test("Automatic publication follows completed Arc and respects overrides",()=>{const {db,arc,actor}=fixture();assert.equal(isPublic(db,actor),false);assert.equal(publicationImpact(db,arc.id).publish>0,true);arc.status="complete";assert.equal(isPublic(db,actor),true);actor.visibility=VISIBILITY.GM;assert.equal(isPublic(db,actor),false);actor.visibility=VISIBILITY.PUBLIC;arc.status="in-progress";assert.equal(isPublic(db,actor),true);});
test("Metaplot secrecy is independent of completed child Arc",()=>{const {db,meta,arc}=fixture();arc.status="complete";assert.equal(isPublic(db,arc),true);assert.equal(isPublic(db,meta),false);});
test("Synopsis links only first exact occurrence",()=>{const {db,session,actor}=fixture();const linked=linkSynopsis(db,session);assert.equal((linked.html.match(new RegExp(`data-wiki-id="${actor.id}"`,"g"))??[]).length,1);assert.match(linked.html,/watched Raven/);});
test("Alias collision creates attention and never guesses",()=>{const {db,session}=fixture();const other=add(db,"actor","John Raven",{classification:"npc",description:"",aliases:["Raven"]});session.memberIds.push(other.id);const result=linkSynopsis(db,session);assert.ok(result.ambiguous.length);assert.ok(deriveAttention(db).some(item=>item.kind===ATTENTION.AMBIGUOUS_LINK));});
test("Player rendering suppresses hidden synopsis target",()=>{const {db,session}=fixture();assert.doesNotMatch(linkSynopsis(db,session,{player:true}).html,/data-wiki-id/);});
test("Historical enrichment suggests and remembers dismissal",()=>{const {db,arc}=fixture();const old=add(db,"session","Old",{arcId:arc.id,playDate:"1937-01-01",synopsis:"Mickey Doyle escaped.",memberIds:[]});const mickey=add(db,"actor","Mickey Doyle",{classification:"npc",description:"Gangster"});const suggestions=historicalSuggestions(db,mickey);assert.equal(suggestions[0].sessionId,old.id);db.resolutions[suggestions[0].id]={action:"ignored"};assert.equal(historicalSuggestions(db,mickey).length,0);});
test("Aliases are GM-searchable but absent from player search",()=>{const {db,actor}=fixture();assert.equal(search(db,"The Raven")[0].entity.id,actor.id);assert.equal(search(db,"The Raven",{player:true}).length,0);});
test("Deleting an Arc deletes Sessions but preserves articles",()=>{const {db,arc,session,actor}=fixture();removeEntity(db,arc.id);assert.equal(db.entities[session.id],undefined);assert.ok(db.entities[actor.id]);});
test("Database integrity catches broken Session Arc",()=>{const {db,session}=fixture();session.arcId="missing";assert.ok(validateDatabase(db).length);});
