import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import * as core from '../modules/hero-rulebook/scripts/rulebook-core.js';
import * as workflow from '../modules/hero-rulebook/scripts/rulebook-import.js';
const source=readFileSync(new URL('../modules/hero-rulebook/scripts/rulebook.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ','');
function runtime(){const hooks={},values={},calls=[],renders=[];const page={id:'p001',label:'1',title:'Intro',sections:[{id:'p001-s01',title:'Intro',text:'Rules',images:[]}]};const book={schemaVersion:1,id:'test',pages:[{id:'p001',label:'1'}],toc:[],glossary:[]};const context={...core,...workflow,esc:core.escapeHtml,structuredClone,Map,Set,console,$:v=>v,Application:class{render(){renders.push(this);return this;}},Hooks:{on:(key,fn)=>hooks[key]=fn},game:{user:{id:'player',isGM:false,getFlag:()=>({})},users:new Map([['gm',{isGM:true}],['player',{isGM:false}]]),settings:{register(_m,key,options){values[key]=options.default;},get:(_m,key)=>values[key]}},fetch:async path=>{calls.push(path);return {ok:true,json:async()=>path.endsWith('book.json')?book:path.endsWith('search.json')?[]:page};},ui:{notifications:{warn(){}}}};vm.createContext(context);vm.runInContext(source+'\nglobalThis.api={installRulebook,openRulebook,renderCollectedRules};',context);context.api.installRulebook({linkText:t=>t});return {context,hooks,calls,renders};}
test('show players accepts authenticated GM updates and ignores forged player requests',async()=>{const r=runtime(),update={flags:{'hero-rulebook':{rulebookShow:{bookId:'test',pageId:'p001',sectionId:'p001-s01'}}}};r.hooks.updateUser({},update,{},'player');await new Promise(setImmediate);assert.equal(r.renders.length,0);r.hooks.updateUser({},update,{},'gm');await new Promise(setImmediate);assert.equal(r.renders.length,1);assert.equal(r.renders[0].sectionId,'p001-s01');});
test('opening a page does not fetch the search index and players cannot modify sections',async()=>{const r=runtime();await r.context.api.openRulebook({pageId:'p001'});const app=r.renders[0];await app._renderInner();assert.ok(r.calls.some(p=>p.endsWith('pages/p001.json')));assert.ok(!r.calls.some(p=>p.endsWith('search.json')));await assert.rejects(()=>app.action({rb:'edit',page:'p001',section:'p001-s01'}),/Only the GM/);});
test('collected article rendering excludes house rules by default and respects player link context',async()=>{const r=runtime();r.context.api.installRulebook({linkText:(text,player)=>`${player?'PLAYER:':'GM:'}${text}`});r.context.game.settings.register('', 'rulebookEdits',{default:{test:{'p001-s01':{houseRule:'Custom rule'}}}});const article={rulebookCollection:{bookId:'test',refs:[{pageId:'p001',sectionId:'p001-s01'}]}};const html=await r.context.api.renderCollectedRules(article,{player:true});assert.match(html,/PLAYER:Rules/);assert.doesNotMatch(html,/Custom rule/);assert.match(html,/data-action="rulebook-ref"/);article.rulebookCollection.refs[0].includeHouseRule=true;assert.match(await r.context.api.renderCollectedRules(article,{player:true}),/Custom rule/);});
test('removed pages disappear from search, contents, glossary and collected sources without fetching page data',async()=>{const r=runtime();await r.context.api.openRulebook();const app=r.renders[0];app.book.toc=[{pageId:'p001',sectionId:'p001-s01',title:'Excluded heading'}];app.book.glossary=[{term:'Excluded term',pageId:'p001',sectionId:'p001-s01',definition:'Definition'}];app.index=[{pageId:'p001',sectionId:'p001-s01',title:'Excluded heading',text:'Rules',label:'1'}];r.context.game.settings.register('', 'rulebookRemovedPages',{default:{test:['p001']}});app.mode='search';app.query='Rules';let html=await app._renderInner();assert.match(html,/0 matching sections/);assert.doesNotMatch(html,/Excluded heading/);app.mode='glossary';assert.doesNotMatch(await app._renderInner(),/Excluded term/);app.mode='page';assert.match(await app._renderInner(),/removed from the active rulebook/);const article={rulebookCollection:{bookId:'test',refs:[{pageId:'p001',sectionId:'p001-s01'}]}};assert.match(await r.context.api.renderCollectedRules(article),/Source page removed/);assert.ok(!r.calls.some(p=>p.endsWith('pages/p001.json')));await assert.rejects(()=>app.action({rb:'manage-pages'}),/Only the GM/);r.context.game.settings.register('', 'rulebookRemovedPages',{default:{test:[]}});app.mode='search';assert.match(await app._renderInner(),/1 matching sections/);assert.match(await r.context.api.renderCollectedRules(article),/Rules/);});
