import test from 'node:test';
import assert from 'node:assert/strict';
import {manualPage,validateBatch,planBatch,buildSearchIndex,uploadBatch,reviewFingerprint,reviewState,moveReference} from '../scripts/rulebook-import.js';
import {continuationChain,searchRules,sectionHtml} from '../scripts/rulebook-core.js';
const first=()=>({id:'p1',label:'1',order:1,title:'Grab',sections:[{id:'s1',title:'Grab',text:'Make a Strength',images:[]}]});
const second=()=>({id:'p2',label:'2',order:2,title:'Grab continued',sections:[{id:'s2',title:'Grab',text:'contest against the target.',images:[],continuesFrom:{pageId:'p1',sectionId:'s1'}}]});
const book=pages=>({schemaVersion:1,id:'hero',title:'Rules',pages:pages.map(p=>({id:p.id,label:p.label,title:p.title,order:p.order})),toc:pages.flatMap(p=>p.sections.map(s=>({pageId:p.id,sectionId:s.id,title:s.title}))),glossary:[]});
const batch=pages=>({format:'hero-rulebook-batch-v1',book:book(pages),pages,assets:[]});
test('manual paste creates stable sections and preserves paragraph breaks',()=>{const p=manualPage({id:'p1',label:'S3',order:3,title:'Skills',text:'## First\nParagraph one.\n\nParagraph two.\n## Second\nMore text.'});assert.equal(p.sections.length,2);assert.equal(p.sections[0].id,'p1-s01');assert.match(p.sections[0].text,/\n\n/);assert.equal(p.label,'S3');assert.throws(()=>manualPage({id:'p1',label:'',title:'x',text:'x',order:1}));});
test('batch append preserves previous IDs and rejects removed section references',()=>{const p1=first(),p2=second(),plan=planBatch(book([p1]),[p1],batch([p2]));assert.deepEqual(plan.pages.map(p=>p.id),['p1','p2']);assert.equal(plan.added,1);assert.equal(plan.replaced,0);const bad=first();bad.sections[0].id='replacement';assert.throws(()=>planBatch(book([p1]),[p1],batch([bad])),/lose section links/);});
test('continuations retain page locations and search across the boundary',()=>{const pages=[first(),second()],rows=buildSearchIndex(pages);assert.deepEqual(continuationChain(rows,rows[1]).map(r=>r.pageId),['p1','p2']);const result=searchRules(rows,'Strength contest');assert.equal(result.length,1);assert.equal(result[0].label,'1–2');assert.equal(result[0].continued,true);assert.equal(result[0].pageId,'p1');});
test('continuations cannot point forward, to missing sections, or fork',()=>{const p1=first(),p2=second();p1.sections[0].continuesFrom={pageId:'p2',sectionId:'s2'};assert.throws(()=>planBatch(null,[],batch([p1,p2])),/earlier page/);const p3={...second(),id:'p3',label:'3',order:3,sections:[{...second().sections[0],id:'s3'}]};assert.throws(()=>planBatch(null,[],batch([first(),second(),p3])),/two different/);});
test('review verification expires on source edits but not house-rule changes',()=>{const p=first(),saved={status:'verified',fingerprint:reviewFingerprint(p)};assert.equal(reviewState(p,saved).status,'verified');p.sections[0].houseRule='Our ruling';assert.equal(reviewState(p,saved).status,'verified');p.sections[0].text+=' correction';assert.equal(reviewState(p,saved).status,'needs-review');});
test('collection references can be reordered without changing inclusion flags',()=>{const refs=[{pageId:'p1',sectionId:'s1',includeHouseRule:true},{pageId:'p2',sectionId:'s2'}];assert.deepEqual(moveReference(refs,'p2:s2',-1),[refs[1],refs[0]]);assert.equal(refs[0].pageId,'p1');});
test('import rejects missing images and unsafe asset paths',()=>{const b=batch([first()]);b.pages[0].sections[0].images=[{src:'images/missing.webp'}];assert.throws(()=>validateBatch(b),/missing/);b.assets=[{path:'../bad.png',mime:'image/png',data:'YWJj'}];assert.throws(()=>validateBatch(b),/Invalid/);});
test('upload only writes changed pages and returns active path after verified manifest',async()=>{const p1=first(),p2=second(),old=book([p1]);old.pages[0].file='https://example.test/old/pages/p1.json';const plan=planBatch(old,[p1],batch([p2])),files=new Map(),calls=[];const result=await uploadBatch(plan,[],{folder:'new',createDirectory:async()=>{},upload:async(folder,name,payload)=>{const path='https://example.test/'+folder+'/'+name;files.set(path,payload.json);calls.push(name);return path;},readJson:async path=>files.get(path)});assert.equal(result,'https://example.test/new');assert.ok(!calls.includes('p1.json'));assert.ok(calls.includes('p2.json'));assert.equal(files.get(result+'/book.json').pages[0].file,old.pages[0].file);assert.equal(files.get(result+'/search.json').length,2);});
test('failed upload never produces an activation path',async()=>{const plan=planBatch(null,[],batch([first()]));await assert.rejects(()=>uploadBatch(plan,[],{folder:'new',createDirectory:async()=>{},upload:async()=>false,readJson:async()=>{throw Error('must not read');}}),/upload failed/);});


test('table OCR remains searchable without interrupting cross-page prose',()=>{const a=first(),b=second();a.sections[0].images=[{src:'images/table.webp',caption:'Reference',searchText:'Obscure table entry 42'}];const rows=buildSearchIndex([a,b]);assert.equal(rows[0].text,'Make a Strength');assert.match(rows[0].imageText,/Obscure/);assert.equal(searchRules(rows,'Strength contest').length,1);assert.equal(searchRules(rows,'Obscure table').length,1);const html=sectionHtml(a.sections[0]);assert.match(html,/<details class="rb-image-ocr">/);assert.doesNotMatch(html,/<details[^>]* open/);assert.equal(searchRules(rows,'Obscure',{overrides:{s1:{images:[]}}}).length,0);assert.equal(searchRules(rows,'Corrected',{overrides:{s1:{images:[{searchText:'Corrected entry'}]}}}).length,1);});
test('image OCR is escaped in reader and rejects nontext import values',()=>{const p=first();p.sections[0].images=[{src:'https://example.test/table.webp',searchText:'<script>alert(1)</script>'}];const html=sectionHtml(p.sections[0]);assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));const b=batch([p]);b.pages[0].sections[0].images[0].searchText={bad:true};assert.throws(()=>validateBatch(b),/search text must be text/);});
