import {UNIFIED_SCHEMA_VERSION,ROOTS,ROOT_IDS,VISIBILITY,emptyUnifiedDatabase,makeArticleId,normalizeArticle,articles,childrenOf,ancestorsOf,descendantsOf,pathsTo,articlePaths,breadcrumb,primaryRoot,derivedDateRange,isPublic,visibleArticles,needsActioning,searchArticles,putArticle,removeArticle,validateUnified,migrateV2} from "./unified-core.js";

const MODULE_ID="campaign-wiki";
const SETTING_DATABASE="databaseV3";
const SETTING_V2="databaseV2";
const FALLBACK_LOGO=`modules/${MODULE_ID}/assets/hero-logo-fallback-wiki-palette.png`;
let app;

const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const today=()=>new Date().toLocaleDateString("en-CA");
const slug=value=>String(value??"").normalize("NFKD").replace(/[^\w]+/g,"-").replace(/^-|-$/g,"").toLowerCase();
const clone=value=>foundry.utils.deepClone(value);
const database=()=>clone(game.settings.get(MODULE_ID,SETTING_DATABASE)||emptyUnifiedDatabase(game.world.id));
async function persist(data){data.schemaVersion=UNIFIED_SCHEMA_VERSION;data.worldId||=game.world.id;await game.settings.set(MODULE_ID,SETTING_DATABASE,data);app?.render(false);}
const viewerIsPlayer=()=>!game.user.isGM;
const canSee=(data,article)=>game.user.isGM||isPublic(data,article);
const sourceDocument=article=>article?.source?.uuid?fromUuidSync(article.source.uuid):null;
const headerImage=article=>article?.tokenImage||FALLBACK_LOGO;
const articleImage=article=>article?.image||"";
const rootLabel=id=>ROOTS.find(root=>root.id===id)?.name??"";
const button=(label,action,id="",icon="",extra="")=>`<button type="button" data-action="${action}"${id?` data-id="${esc(id)}"`:""}${extra}>${icon?`<i class="fas ${icon}"></i>`:""}${esc(label)}</button>`;

function navigationSorter(data,rootId){if(rootId!=="root:metaplots"&&rootId!=="root:arcs")return(a,b)=>a.title.localeCompare(b.title);return(a,b)=>{const aDate=derivedDateRange(data,a.id)?.end??a.date??"",bDate=derivedDateRange(data,b.id)?.end??b.date??"";return bDate.localeCompare(aDate)||a.title.localeCompare(b.title);};}
function navArticle(data,article,allowed,open,path,rootId,depth=1,trail=new Set()){
  if(trail.has(article.id))return"";const nextTrail=new Set(trail).add(article.id),stopAtTerminal=(rootId==="root:metaplots"||rootId==="root:arcs")&&depth>=2,children=(stopAtTerminal?[]:childrenOf(data,article.id)).filter(child=>allowed.has(child.id)).sort(navigationSorter(data,rootId));
  if(!children.length)return `<button class="cw-nav-leaf" data-action="open" data-id="${article.id}" data-path="${esc(JSON.stringify(path))}">${esc(article.title)}</button>`;
  const key=`article:${article.id}`;return `<details data-nav-key="${key}"${open.has(key)?" open":""}><summary><span class="cw-nav-toggle" aria-hidden="true"><i class="fas fa-chevron-right"></i></span><button type="button" data-action="open" data-id="${article.id}" data-path="${esc(JSON.stringify(path))}">${esc(article.title)}</button></summary><div class="cw-nav-children">${children.map(child=>navArticle(data,child,allowed,open,[...path,child.id],rootId,depth+1,nextTrail)).join("")}</div></details>`;
}
function navigation(data,open){const visible=visibleArticles(data,viewerIsPlayer()),visibleIds=new Set(visible.map(article=>article.id));return `<nav class="cw-nav"><button class="cw-home-button" data-action="home"><i class="fas fa-home"></i> Home</button>${ROOTS.map(root=>{let allowed=new Set(visible.filter(article=>primaryRoot(data,article)===root.id).map(article=>article.id)),children=childrenOf(data,root.id).filter(article=>allowed.has(article.id));if(root.id==="root:arcs"){const metaplotArcs=visible.filter(article=>articlePaths(data,article).some(path=>path[0]==="root:metaplots"&&path.length===3));children=[...new Map([...children,...metaplotArcs].map(article=>[article.id,article])).values()];allowed=new Set(children.map(article=>article.id));for(const arc of children)for(const session of childrenOf(data,arc.id))if(visibleIds.has(session.id))allowed.add(session.id);}children.sort(navigationSorter(data,root.id));if(root.id==="root:metaplots"&&!children.length)return"";const key=`root:${root.id}`;return `<details data-nav-key="${key}"${open.has(key)?" open":""}><summary><span class="cw-nav-toggle" aria-hidden="true"><i class="fas fa-chevron-right"></i></span><span class="cw-nav-label">${esc(root.name)}</span></summary><div class="cw-nav-children">${children.map(child=>navArticle(data,child,allowed,open,[root.id,child.id],root.id)).join("")}</div></details>`;}).join("")}</nav>`;}

function card(article){return `<button class="cw-card" data-action="open" data-id="${article.id}">${article.image?`<img src="${esc(article.image)}">`:""}<span><strong>${esc(article.title)}</strong>${article.date?`<small>${article.date}</small>`:""}</span></button>`;}
function homeHtml(data){const attention=game.user.isGM?needsActioning(data):[],recent=visibleArticles(data,viewerIsPlayer()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,12);return `<article class="cw-home"><header><h1>Campaign Wiki</h1><p>The campaign record.</p></header>${game.user.isGM?`<section><h2>Needs Actioning <span>${attention.length}</span></h2><div class="cw-attention">${attention.length?attention.map(item=>{const article=data.articles[item.articleId];return `<div class="cw-attention-item"><button data-action="open" data-id="${article.id}"><strong>${esc(item.kind)}</strong><span>${esc(article.title)}</span></button>${button("Edit","edit",article.id)}</div>`;}).join(""):'<p class="cw-empty">Nothing needs actioning.</p>'}</div></section>`:""}<section><h2>Recently Added</h2><div class="cw-cards">${recent.length?recent.map(card).join(""):'<p class="cw-empty">No Articles yet.</p>'}</div></section></article>`;}
function visibilityLabel(data,article){if(article.visibility===VISIBILITY.PUBLIC)return"Public";if(article.visibility===VISIBILITY.GM)return"GM Only";return `Automatic · ${isPublic(data,article)?"Public":"GM Only"}`;}
function breadcrumbRows(data,article,requestedPath){const paths=articlePaths(data,article),path=paths.some(candidate=>JSON.stringify(candidate)===JSON.stringify(requestedPath))?requestedPath:paths.sort((a,b)=>a.length-b.length||breadcrumb(data,a).join("/").localeCompare(breadcrumb(data,b).join("/")))[0],visibility=visibilityLabel(data,article);return path?`<div class="cw-breadcrumb"><span class="cw-breadcrumb-path">${breadcrumb(data,path).map(esc).join(" <span>›</span> ")}</span><span class="cw-breadcrumb-visibility">${esc(visibility)}</span></div>`:"";}
function articleRole(data,article){if(article.source?.documentType==="Actor"||article.legacy?.type==="actor")return"person";if(article.source?.documentType==="Scene"||["scene","area"].includes(article.legacy?.type))return"place";if(article.legacy?.type==="image")return"image";if(article.legacy?.type==="affiliation")return"affiliation";const paths=articlePaths(data,article),metaplotPath=paths.find(path=>path[0]==="root:metaplots"),arcPath=paths.find(path=>path[0]==="root:arcs");if(metaplotPath)return metaplotPath.length===2?"metaplot":metaplotPath.length===3?"arc":"session";if(arcPath)return arcPath.length===2?"arc":"session";const root=primaryRoot(data,article);if(root==="root:images")return article.organizer?"image-category":"image";if(root==="root:people")return article.organizer?"people-category":"person";if(root==="root:places")return"place";return"article";}
function relationshipLabel(data,related,direction){const role=articleRole(data,related);if(direction==="parent"){if(role==="session")return"Featured in";if(role==="arc")return"Part of Arc";if(role==="metaplot")return"Part of Metaplot";if(role==="place")return"Located in";if(role==="affiliation"||role==="people-category"&&related.title.toLocaleLowerCase().includes("affiliation"))return"Affiliated with";if(role==="person")return"Associated with";if(role==="image-category")return"Image Category";if(role==="people-category")return"People Category";return"Related to";}if(role==="session")return"Sessions";if(role==="arc")return"Arcs";if(role==="image")return"Featured Images";if(role==="place")return"Featured Places";if(role==="person")return"Featured People";if(role==="affiliation")return"Affiliations";return"Featuring";}
function relationshipPath(data,article){return articlePaths(data,article).sort((a,b)=>a.length-b.length||breadcrumb(data,a).join("/").localeCompare(breadcrumb(data,b).join("/")))[0]??null;}
function relationshipSections(data,article){const parentIds=article.parentIds.filter(id=>!ROOT_IDS.has(id)&&!article.parentIds.some(other=>other!==id&&!ROOT_IDS.has(other)&&ancestorsOf(data,other).includes(id))),directChildren=childrenOf(data,article.id).filter(child=>!child.parentIds.some(other=>other!==article.id&&!ROOT_IDS.has(other)&&ancestorsOf(data,other).includes(article.id))),related=[...parentIds.map(id=>({article:data.articles[id],direction:"parent"})),...directChildren.map(child=>({article:child,direction:"child"}))].filter(item=>item.article&&canSee(data,item.article)),groups=new Map();for(const item of related){const label=relationshipLabel(data,item.article,item.direction);if(!groups.has(label))groups.set(label,[]);groups.get(label).push(item.article);}return [...groups].map(([label,items])=>{const chronological=["Featured in","Part of Arc","Part of Metaplot","Sessions","Arcs"].includes(label),sorter=chronological?navigationSorter(data,"root:arcs"):(a,b)=>a.title.localeCompare(b.title);return `<section class="cw-relationship-section"><h2>${esc(label)}</h2><div class="cw-relationship-list">${items.sort(sorter).map(item=>{const path=relationshipPath(data,item),thumbnail=item.image||item.tokenImage||FALLBACK_LOGO;return `<button type="button" class="cw-relationship-card" data-action="open" data-id="${item.id}"${path?` data-path="${esc(JSON.stringify(path))}"`:""}><img src="${esc(thumbnail)}" alt=""><span>${esc(item.title)}</span></button>`;}).join("")}</div></section>`;}).join("");}
function articleHtml(data,article,currentPath){if(!article||!canSee(data,article))return'<article class="cw-unavailable"><h1>Article unavailable</h1></article>';const source=sourceDocument(article),range=derivedDateRange(data,article.id),shownDate=article.date||(range?(range.start===range.end?range.start:`${range.start} – ${article.status==="in-progress"?"Present":range.end}`):""),hasText=Boolean(article.text.trim()),relationships=relationshipSections(data,article);return `<article class="cw-article cw-unified-article"><header class="cw-unified-header"><img src="${esc(headerImage(article))}" alt=""><h1>${esc(article.title)}</h1></header><div class="cw-breadcrumbs">${breadcrumbRows(data,article,currentPath)}</div>${shownDate||article.status?`<div class="cw-article-meta">${shownDate?`<span><i class="fas fa-calendar"></i> ${shownDate}${!article.date&&range?" (derived)":""}</span>`:""}${article.status?`<span>${article.status==="complete"?"Complete":"In Progress"}</span>`:""}</div>`:""}<div class="cw-unified-body">${article.image?`<img class="cw-article-image" src="${esc(article.image)}" alt="">`:""}${hasText||!article.image?`<div class="cw-description">${hasText?esc(article.text).replace(/\n/g,"<br>"):'<span class="cw-empty">No article text yet.</span>'}</div>`:""}</div>${relationships?`<div class="cw-relationships">${relationships}</div>`:""}<footer>${source?button("Open in Foundry","open-source",article.id,"fa-external-link-alt"):""}${game.user.isGM?button("New Child Article","new-child",article.id,"fa-plus")+button("Edit Article","edit",article.id,"fa-edit")+button("Delete","delete",article.id,"fa-trash"):""}</footer></article>`;}
function searchHtml(data,query){const results=searchArticles(data,query,{player:viewerIsPlayer()});return `<article class="cw-search"><h1>Search</h1><p>${results.length} result(s) for “${esc(query)}”</p>${results.map(result=>`<button data-action="open" data-id="${result.article.id}"><strong>${esc(result.article.title)}</strong><span>${result.match}${result.alias?`: ${esc(result.alias)}`:""}</span></button>`).join("")||'<p class="cw-empty">Nothing found.</p>'}</article>`;}

class CampaignWikiApp extends Application{
  constructor(options={}){super(options);this.currentId=null;this.currentPath=null;this.query="";this.openNavigation=new Set();}
  static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{id:"campaign-wiki-app",title:"Campaign Wiki",width:1280,height:800,resizable:true,popOut:true,classes:["campaign-wiki"]});}
  async _renderInner(){const data=database(),content=this.query?searchHtml(data,this.query):this.currentId?articleHtml(data,data.articles[this.currentId],this.currentPath):homeHtml(data);return $(`<div class="cw-shell"><aside>${navigation(data,this.openNavigation)}</aside><main><div class="cw-toolbar"><form data-search><input name="query" placeholder="Search Campaign Wiki" value="${esc(this.query)}"><button><i class="fas fa-search"></i></button></form>${game.user.isGM?button("New Article","new-article","","fa-plus")+`<button type="button" data-action="edit" data-id="${this.currentId??""}"${this.currentId?"":" disabled"}><i class="fas fa-edit"></i>Edit Article</button>`:""}</div><div class="cw-content">${content}</div></main></div>`);}
  activateListeners(html){super.activateListeners(html);html.on("click","[data-action]",event=>this.action(event));html.find("details[data-nav-key]").each((_index,details)=>details.addEventListener("toggle",()=>details.open?this.openNavigation.add(details.dataset.navKey):this.openNavigation.delete(details.dataset.navKey)));html.on("submit","[data-search]",event=>{event.preventDefault();this.query=new FormData(event.currentTarget).get("query");this.currentId=null;this.render(false);});}
  async action(event){event.preventDefault();event.stopPropagation();const {action,id,path}=event.currentTarget.dataset;if(action==="home"){this.currentId=null;this.currentPath=null;this.query="";return this.render(false);}if(action==="open"){this.currentId=id;this.currentPath=path?JSON.parse(path):null;this.query="";return this.render(false);}if(action==="new-article")return editArticle();if(action==="edit"&&id)return editArticle(database().articles[id]);if(action==="new-child")return newChild(id);if(action==="delete")return deleteArticle(id);if(action==="open-source")return sourceDocument(database().articles[id])?.sheet?.render(true);}
}

function dialogForm(title,content,{width=820,height="auto",onRender}={}){return new Promise(resolve=>new Dialog({title,content:`<form class="cw-form cw-unified-form">${content}</form>`,buttons:{save:{icon:'<i class="fas fa-save"></i>',label:"Save",callback:html=>resolve(new FormData(html.find("form")[0]))},cancel:{label:"Cancel",callback:()=>resolve(null)}},default:"save",close:()=>resolve(null),render:html=>onRender?.(html)}, {width,height,classes:["dialog","campaign-wiki-dialog"]}).render(true));}
function shortestPathTo(data,parentId){if(ROOT_IDS.has(parentId))return[parentId];return pathsTo(data,parentId).sort((a,b)=>a.length-b.length)[0]??["root:people"];}
function parentPickerHtml(article){return `<fieldset class="cw-parent-picker" data-parent-picker data-article-id="${article?.id??""}" data-parents="${esc(JSON.stringify(article?.parentIds??[]))}"><legend>Parent Article Paths</legend><div data-parent-rows></div><button type="button" data-add-parent><i class="fas fa-plus"></i> Add Parent Path</button><p>Each path selects one immediate parent. An Article may appear beneath several parents.</p></fieldset>`;}
function setupParentPicker(html,data,article){const picker=html.find("[data-parent-picker]")[0],rows=picker.querySelector("[data-parent-rows]"),blocked=new Set(article?.id?[article.id,...descendantsOf(data,article.id)]:[]);let states=(article?.parentIds?.length?article.parentIds:["root:people"]).map(parentId=>shortestPathTo(data,parentId));const render=()=>{rows.innerHTML="";states.forEach((state,index)=>{const row=document.createElement("div");row.className="cw-parent-row";const root=document.createElement("select");root.innerHTML=ROOTS.map(item=>`<option value="${item.id}"${state[0]===item.id?" selected":""}>${esc(item.name)}</option>`).join("");root.onchange=()=>{states[index]=[root.value];render();};row.append(root);for(let depth=0;depth<state.length;depth++){const parentId=state[depth],choices=childrenOf(data,parentId).filter(item=>!blocked.has(item.id)).sort((a,b)=>a.title.localeCompare(b.title));if(!choices.length)continue;const select=document.createElement("select"),next=state[depth+1]??"";select.innerHTML=`<option value="">Use ${esc(ROOT_IDS.has(parentId)?rootLabel(parentId):data.articles[parentId]?.title)} as parent</option>${choices.map(item=>`<option value="${item.id}"${next===item.id?" selected":""}>${esc(item.title)}</option>`).join("")}`;select.onchange=()=>{states[index]=state.slice(0,depth+1);if(select.value)states[index].push(select.value);render();};row.append(select);}const hidden=document.createElement("input");hidden.type="hidden";hidden.name="parentIds";hidden.value=state.at(-1);row.append(hidden);if(states.length>1){const remove=document.createElement("button");remove.type="button";remove.innerHTML='<i class="fas fa-trash"></i>';remove.onclick=()=>{states.splice(index,1);render();};row.append(remove);}rows.append(row);});};picker.querySelector("[data-add-parent]").onclick=()=>{states.push(["root:people"]);render();};render();}
function articleForm(data,article){return `<div class="cw-form-header"><img src="${esc(headerImage(article))}" alt=""><label>Article Title<input class="cw-title-input" name="title" required value="${esc(article.title)}"></label></div>${parentPickerHtml(article)}<div class="cw-form-meta"><label>Date<input type="date" name="date" value="${esc(article.date)}"></label><label>Status<select name="status"><option value="">Not applicable</option><option value="in-progress"${article.status==="in-progress"?" selected":""}>In Progress</option><option value="complete"${article.status==="complete"?" selected":""}>Complete</option></select></label><label>Visibility<select name="visibility"><option value="automatic"${article.visibility==="automatic"?" selected":""}>Automatic</option><option value="always-public"${article.visibility==="always-public"?" selected":""}>Always Public</option><option value="always-gm"${article.visibility==="always-gm"?" selected":""}>Always GM Only</option></select></label></div><div class="cw-form-body"><div><label>Article Image<div class="cw-file"><input name="image" value="${esc(article.image)}"><button type="button" data-file><i class="fas fa-folder-open"></i></button></div></label><img data-image-preview src="${esc(article.image||FALLBACK_LOGO)}" alt=""></div><label>Article Text<textarea name="text" rows="16">${esc(article.text)}</textarea></label></div><details><summary>Aliases</summary><label>One per line<textarea name="aliases" rows="4">${esc(article.aliases.join("\n"))}</textarea></label></details>${article.source?`<p class="cw-source"><strong>Foundry source:</strong> ${esc(article.source.uuid)}${article.source.missing?" — Missing":""}</p>`:""}`;}
async function editArticle(existing=null){const data=database(),article=normalizeArticle(existing??{id:makeArticleId(),title:"",parentIds:["root:people"],text:"",image:"",aliases:[],visibility:VISIBILITY.AUTOMATIC,date:"",status:"",placeholder:false});const form=await dialogForm(existing?"Edit Article":"New Article",articleForm(data,article),{height:Math.min(760,window.innerHeight-80),onRender:html=>{setupParentPicker(html,data,article);html.on("click","[data-file]",()=>new FilePicker({type:"image",callback:path=>{html.find("[name=image]").val(path);html.find("[data-image-preview]").attr("src",path);}}).render(true));html.on("input","[name=image]",event=>html.find("[data-image-preview]").attr("src",event.currentTarget.value||FALLBACK_LOGO));}});if(!form)return;try{const current=database(),saved=putArticle(current,{...article,title:form.get("title"),parentIds:[...new Set(form.getAll("parentIds"))],date:form.get("date"),status:form.get("status"),visibility:form.get("visibility"),image:form.get("image"),text:form.get("text"),aliases:String(form.get("aliases")??"").split(/\r?\n/).map(value=>value.trim()).filter(Boolean),placeholder:false});await persist(current);app.currentId=saved.id;}catch(error){ui.notifications.error(error.message);}}
async function newChild(parentId){const data=database(),parent=data.articles[parentId];if(!parent)return;const form=await dialogForm("New Child Article",`<p>This creates a title-only placeholder beneath <strong>${esc(parent.title)}</strong> and adds it to Needs Actioning.</p><label>Article Title<input name="title" required></label>`,{width:460});if(!form)return;try{const current=database(),child=putArticle(current,{id:makeArticleId(),title:form.get("title"),parentIds:[parentId],text:"",image:"",aliases:[],visibility:VISIBILITY.AUTOMATIC,placeholder:true});await persist(current);app.currentId=child.id;}catch(error){ui.notifications.error(error.message);}}
async function deleteArticle(id){const data=database(),article=data.articles[id];if(!article)return;const children=childrenOf(data,id);if(!await confirmAction(`Delete ${article.title}?`,`${children.length} child Article(s) will inherit this Article's parents. The Foundry source will not be deleted.`))return;for(const child of children)child.parentIds=[...new Set([...child.parentIds.filter(parentId=>parentId!==id),...article.parentIds])];removeArticle(data,id);await persist(data);app.currentId=null;}
function confirmAction(title,content){return new Promise(resolve=>new Dialog({title,content:`<p>${esc(content)}</p>`,buttons:{yes:{label:"Confirm",callback:()=>resolve(true)},no:{label:"Cancel",callback:()=>resolve(false)}},default:"no",close:()=>resolve(false)}).render(true));}

function saveBlob(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportPackage(data=database()){saveBlob(JSON.stringify({format:"campaign-wiki-unified",version:3,exportedAt:new Date().toISOString(),database:data},null,2),"application/json",`${slug(game.world.title)}-campaign-wiki-${today()}.json`);}
function importPackage(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=async()=>{try{const payload=JSON.parse(await input.files[0].text()),incoming=payload.database??payload,errors=validateUnified(incoming);if(errors.length)throw new Error(errors.join("\n"));exportPackage();await persist(incoming);ui.notifications.info("Campaign Wiki imported after automatic backup.");}catch(error){ui.notifications.error(error.message);}};input.click();}
async function offerV2Migration(){const current=database();if(Object.keys(current.articles).length||current.migration)return;let v2;try{v2=game.settings.get(MODULE_ID,SETTING_V2);}catch{return;}if(!v2?.entities||!Object.keys(v2.entities).length)return;if(!await confirmAction("Create unified Campaign Wiki?","Your v2 data will be downloaded unchanged, then converted conservatively into the unified multi-parent Article model. The v2 world setting and legacy overlay remain untouched."))return;saveBlob(JSON.stringify(v2,null,2),"application/json",`${slug(game.world.title)}-campaign-wiki-v2-backup-${today()}.json`);const result=migrateV2(v2,game.world.id);await persist(result.database);ui.notifications.info(`Created ${result.stats.articles} Articles and ${result.stats.parentLinks} exact parent links. Unfinished placeholders are in Needs Actioning.`);}

function sourceArticle(data,documentType,id){return articles(data).find(article=>article.source?.documentType===documentType&&article.source.id===id);}
async function createSourceArticle(documentType,document){if(!game.user.isGM)return;const data=database();if(sourceArticle(data,documentType,document.id))return;putArticle(data,{id:makeArticleId(),title:document.name,parentIds:[documentType==="Actor"?"root:people":"root:places"],text:"",image:documentType==="Actor"?document.img:(document.background?.src||document.img||""),tokenImage:documentType==="Actor"?(document.prototypeToken?.texture?.src||""):"",aliases:[],visibility:VISIBILITY.AUTOMATIC,placeholder:true,source:{documentType,uuid:document.uuid,id:document.id,missing:false}});await persist(data);}
async function syncSource(documentType,document){if(!game.user.isGM)return;const data=database(),article=sourceArticle(data,documentType,document.id);if(!article)return;if(article.title!==document.name){article.aliases=[...new Set([...article.aliases,article.title])];article.title=document.name;}article.image=documentType==="Actor"?document.img:(document.background?.src||document.img||"");if(documentType==="Actor")article.tokenImage=document.prototypeToken?.texture?.src||"";article.source.missing=false;await persist(data);}
async function missingSource(documentType,document){if(!game.user.isGM)return;const data=database(),article=sourceArticle(data,documentType,document.id);if(article){article.source.missing=true;await persist(data);}}

function installLauncher(){let launcher=document.querySelector("#campaign-wiki-launcher");if(!launcher){launcher=document.createElement("button");launcher.id="campaign-wiki-launcher";launcher.type="button";launcher.innerHTML='<i class="fas fa-book-open"></i><span>Campaign Wiki</span>';launcher.onclick=openWiki;document.body.append(launcher);}positionLauncher();}
function positionLauncher(){const launcher=document.querySelector("#campaign-wiki-launcher"),players=document.querySelector("#players"),rect=players?.getBoundingClientRect();if(!launcher)return;launcher.style.left=rect?.right>0?`${Math.round(rect.right+10)}px`:"228px";launcher.style.bottom=rect?.bottom>0?`${Math.max(8,Math.round(window.innerHeight-rect.bottom))}px`:"12px";}
function openWiki(){app??=new CampaignWikiApp();app.currentId=null;app.currentPath=null;app.query="";app.openNavigation.clear();app.render(true);}
class OpenMenu extends FormApplication{render(){openWiki();return this;}}class ExportMenu extends FormApplication{render(){exportPackage();return this;}}class ImportMenu extends FormApplication{render(){importPackage();return this;}}

Hooks.once("init",()=>{game.settings.register(MODULE_ID,SETTING_DATABASE,{scope:"world",config:false,type:Object,default:emptyUnifiedDatabase()});game.settings.register(MODULE_ID,SETTING_V2,{scope:"world",config:false,type:Object,default:{}});game.settings.registerMenu(MODULE_ID,"openWiki",{name:"Open Campaign Wiki",label:"Open",hint:"Open Campaign Wiki on Home.",icon:"fas fa-book-open",type:OpenMenu,restricted:false});game.settings.registerMenu(MODULE_ID,"exportWiki",{name:"Export Campaign Wiki",label:"Export",hint:"Download this world's unified Campaign Wiki.",icon:"fas fa-download",type:ExportMenu,restricted:true});game.settings.registerMenu(MODULE_ID,"importWiki",{name:"Import Campaign Wiki",label:"Import",hint:"Back up and replace this world's unified Campaign Wiki.",icon:"fas fa-upload",type:ImportMenu,restricted:true});game.modules.get(MODULE_ID).api={open:openWiki,getDatabase:database,put:async input=>{const data=database(),result=putArticle(data,input);await persist(data);return result;},export:exportPackage};});
Hooks.once("ready",async()=>{ui.campaignWiki={open:openWiki,render:openWiki};installLauncher();window.addEventListener("resize",positionLauncher);if(game.user.isGM)await offerV2Migration();});Hooks.on("renderSidebar",installLauncher);Hooks.on("collapseSidebar",()=>setTimeout(positionLauncher,100));Hooks.on("createActor",document=>createSourceArticle("Actor",document));Hooks.on("createScene",document=>createSourceArticle("Scene",document));Hooks.on("updateActor",document=>syncSource("Actor",document));Hooks.on("updateScene",document=>syncSource("Scene",document));Hooks.on("deleteActor",document=>missingSource("Actor",document));Hooks.on("deleteScene",document=>missingSource("Scene",document));
