import { SCHEMA_VERSION, ENTITY_TYPES, VISIBILITY, ATTENTION, emptyDatabase, makeId, putEntity, removeEntity, entitiesOf, arcSessions, metaplotArcs, arcDates, expandedSessionMembers, inheritedMembers, isPublic, publicationImpact, linkSynopsis, deriveAttention, historicalSuggestions, search, validateDatabase } from "./core.js";
import { recoverLegacy } from "./legacy-recovery.js";

const MODULE_ID = "campaign-wiki";
const SETTING_DATABASE = "databaseV2";
const SETTING_LEGACY_OVERLAY = "overlay";
const LABELS = { actor: "Actor", scene: "Scene", image: "Image", area: "Area", affiliation: "Affiliation", arc: "Arc", session: "Session" };
const ATTENTION_LABELS = { "incomplete-actor":"Incomplete Actor","incomplete-scene":"Incomplete Scene","incomplete-image":"Incomplete Image","incomplete-area":"Incomplete Area","incomplete-affiliation":"Incomplete Affiliation","missing-foundry-source":"Missing Foundry Source","missing-session-art":"Missing Session Art","missing-synopsis":"Missing Synopsis","missing-arc-art":"Missing Arc Art","ambiguous-synopsis-link":"Ambiguous Synopsis Link","possible-previous-appearance":"Possible Previous Appearance","possible-match":"Possible Match","migration-remediation":"Migration Remediation","ambiguous-dnpc-owner":"Ambiguous DNPC Owner" };
let app;

const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const slug = value => String(value ?? "").normalize("NFKD").replace(/[^\w]+/g,"-").replace(/^-|-$/g,"").toLowerCase();
const database = () => foundry.utils.deepClone(game.settings.get(MODULE_ID, SETTING_DATABASE) || emptyDatabase(game.world.id));
async function persist(data) { data.schemaVersion=SCHEMA_VERSION; data.worldId ||= game.world.id; await game.settings.set(MODULE_ID,SETTING_DATABASE,data); app?.render(false); }
const today = () => new Date().toLocaleDateString("en-CA");
const image = item => item?.art || item?.portrait || "";
const option = (value,label,selected=false) => `<option value="${esc(value)}"${selected?" selected":""}>${esc(label)}</option>`;
const button = (label,action,id="",icon="") => `<button type="button" data-action="${action}"${id?` data-id="${esc(id)}"`:""}>${icon?`<i class="fas ${icon}"></i>`:""}${esc(label)}</button>`;
const visible = (data,item) => game.user.isGM || isPublic(data,item);
const badges = (data,ids) => ids.map(id=>data.entities[id]).filter(item=>item&&visible(data,item)).map(item=>`<button class="cw-badge" data-action="open" data-id="${item.id}">${esc(item.name)}</button>`).join("");
const fileField = (name,value,label) => `<label>${label}<div class="cw-file"><input name="${name}" value="${esc(value)}"><button type="button" data-file="${name}"><i class="fas fa-folder-open"></i></button></div></label>`;

function cards(items,empty="Nothing here yet.") { return items.length?items.map(item=>`<button class="cw-card" data-action="open" data-id="${item.id}">${image(item)?`<img src="${esc(image(item))}">`:""}<span><strong>${esc(item.name)}</strong>${item.playDate?`<small>${item.playDate}</small>`:""}</span></button>`).join(""):`<p class="cw-empty">${empty}</p>`; }
function homeHtml(data) {
  const arcs=entitiesOf(data,"arc").filter(item=>item.status==="in-progress"&&visible(data,item));
  const sessions=entitiesOf(data,"session").filter(item=>visible(data,item)).sort((a,b)=>b.playDate.localeCompare(a.playDate)).slice(0,10);
  const recent=Object.values(data.entities).filter(item=>!["arc","session"].includes(item.type)&&visible(data,item)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,10);
  const attention=game.user.isGM?[...deriveAttention(data),...Object.values(data.entities).flatMap(item=>historicalSuggestions(data,item))]:[];
  return `<article class="cw-home"><header><h1>Campaign Wiki</h1><p>${game.user.isGM?"The campaign record, organized around what happened at the table.":"The story so far."}</p></header>${game.user.isGM?`<section><h2>Needs Attention <span>${attention.length}</span></h2><div class="cw-attention">${attention.length?attention.slice(0,20).map(item=>attentionHtml(data,item)).join(""):'<p class="cw-empty">Nothing needs attention.</p>'}</div></section>`:""}<section><h2>In Progress</h2><div class="cw-cards">${cards(arcs,"No campaign threads are in progress.")}</div></section><section><h2>Recent Sessions</h2><div class="cw-cards">${cards(sessions,"No Sessions yet.")}</div></section>${game.user.isGM?`<section><h2>Recently Added</h2><div class="cw-cards">${cards(recent,"No articles yet.")}</div></section>`:""}</article>`;
}
function attentionHtml(data,item) { const target=data.entities[item.entityId]; return `<div class="cw-attention-item"><button data-action="open" data-id="${item.entityId}"><strong>${esc(ATTENTION_LABELS[item.kind]??item.kind)}</strong><span>${esc(target?.name??"Unknown article")}${item.text?` — “${esc(item.text)}”`:""}</span></button>${item.kind===ATTENTION.PREVIOUS_APPEARANCE?`${button("Add","accept-history",item.id)}${button("Ignore","resolve-attention",item.id)}`:item.kind===ATTENTION.AMBIGUOUS_LINK?button("Resolve","resolve-link",item.id):button("Review","open",item.entityId)}</div>`; }

const alpha=(a,b)=>a.name.localeCompare(b.name);const newest=(data,a,b)=>(arcDates(data,b)?.end??"").localeCompare(arcDates(data,a)?.end??"")||alpha(a,b);
function navDetails(key,label,content,count,openKeys,addType=""){if(!content&&!addType)return"";return `<details data-nav-key="${key}"${openKeys.has(key)?" open":""}><summary><span>${esc(label)}</span>${count!==null?`<small>${count}</small>`:""}</summary><div class="cw-nav-children">${content}${game.user.isGM&&addType?`<button class="cw-add" data-action="new" data-type="${addType}">+ New ${LABELS[addType]}</button>`:""}</div></details>`;}
const navLeaf=item=>`<button class="cw-nav-leaf" data-action="open" data-id="${item.id}">${esc(item.name)}</button>`;
function actorLeaves(data,actors,openKeys){return actors.sort(alpha).map(actor=>{const dnpcs=entitiesOf(data,"actor").filter(item=>item.dnpcOwnerId===actor.id&&visible(data,item)).sort(alpha);return dnpcs.length?navDetails(`actor:${actor.id}`,actor.name,dnpcs.map(navLeaf).join(""),null,openKeys):navLeaf(actor);}).join("");}
function areaNode(data,area,areas,scenes,openKeys){const children=areas.filter(item=>item.parentAreaId===area.id).sort(alpha).map(item=>areaNode(data,item,areas,scenes,openKeys)).join("");const contained=scenes.filter(item=>item.areaId===area.id).sort(alpha).map(navLeaf).join("");return navDetails(`area:${area.id}`,area.name,children+contained,null,openKeys);}
function navHtml(data,openKeys=new Set()) {
  const items=Object.values(data.entities).filter(item=>visible(data,item)),actors=entitiesOf(data,"actor").filter(item=>visible(data,item)),areas=entitiesOf(data,"area").filter(item=>visible(data,item)),scenes=entitiesOf(data,"scene").filter(item=>visible(data,item)),images=entitiesOf(data,"image").filter(item=>visible(data,item));
  const arcs=entitiesOf(data,"arc").filter(item=>item.arcType==="arc"&&visible(data,item)).sort((a,b)=>newest(data,a,b)),metaplots=entitiesOf(data,"arc").filter(item=>item.arcType==="metaplot"&&visible(data,item)).sort((a,b)=>newest(data,a,b));
  const metaplotContent=metaplots.map(meta=>navDetails(`metaplot:${meta.id}`,meta.name,metaplotArcs(data,meta.id).filter(item=>visible(data,item)).sort((a,b)=>newest(data,a,b)).map(navLeaf).join(""),null,openKeys)).join("");
  const rootAreas=areas.filter(item=>!item.parentAreaId||!data.entities[item.parentAreaId]).sort(alpha).map(item=>areaNode(data,item,areas,scenes,openKeys)).join("");const orphanScenes=scenes.filter(item=>!item.areaId||!data.entities[item.areaId]).sort(alpha).map(navLeaf).join("");
  const heroes=actors.filter(item=>item.classification==="hero"&&!item.dnpcOwnerId),villains=actors.filter(item=>item.classification==="villain"&&!item.dnpcOwnerId),npcs=actors.filter(item=>item.classification==="npc"&&!item.dnpcOwnerId),affiliations=entitiesOf(data,"affiliation").filter(item=>visible(data,item)).sort(alpha);
  const people=navDetails("people:heroes","Heroes",actorLeaves(data,heroes,openKeys),heroes.length,openKeys,"actor")+navDetails("people:villains","Villains",actorLeaves(data,villains,openKeys),villains.length,openKeys,"actor")+navDetails("people:npcs","NPCs",actorLeaves(data,npcs,openKeys),npcs.length,openKeys,"actor")+navDetails("people:affiliations","Affiliations",affiliations.map(navLeaf).join(""),affiliations.length,openKeys,"affiliation");
  const imageGroups=[["equipment","Equipment"],["macguffin","MacGuffins"],["media","Media"],["vehicle","Vehicles"],["other","Other"]].map(([kind,label])=>{const group=images.filter(item=>item.classification===kind).sort(alpha);return navDetails(`images:${kind}`,label,group.map(navLeaf).join(""),group.length,openKeys,"image");}).join("");
  return `<nav class="cw-nav"><button class="cw-home-button" data-action="home"><i class="fas fa-home"></i> Home</button>${metaplots.length?navDetails("metaplots","Metaplots",metaplotContent,metaplots.length,openKeys):""}${navDetails("arcs","Arcs",arcs.map(navLeaf).join(""),arcs.length,openKeys,"arc")}${navDetails("places","Places",rootAreas+orphanScenes,areas.length+scenes.length,openKeys,"area")}${navDetails("people","People",people,actors.length+affiliations.length,openKeys)}${navDetails("images","Images",imageGroups,images.length,openKeys)}</nav>`;
}
function articleHtml(data,item) {
  if(!item||!visible(data,item))return'<article class="cw-unavailable"><h1>Article unavailable</h1></article>';
  if(item.type==="session")return sessionHtml(data,item); if(item.type==="arc")return arcHtml(data,item);
  const appearances=entitiesOf(data,"session").filter(s=>expandedSessionMembers(data,s).includes(item.id)&&visible(data,s)); let specific="";
  if(item.type==="actor") { const owner=data.entities[item.dnpcOwnerId]; const dnpcs=entitiesOf(data,"actor").filter(a=>a.dnpcOwnerId===item.id&&visible(data,a)); specific=`${item.tokenArt?`<img class="cw-token" src="${esc(item.tokenArt)}">`:""}${item.quote?`<blockquote>${esc(item.quote)}</blockquote>`:""}${owner&&visible(data,owner)?`<p><strong>DNPC of:</strong> ${badges(data,[owner.id])}</p>`:""}${dnpcs.length?`<section><h2>DNPCs</h2>${badges(data,dnpcs.map(i=>i.id))}</section>`:""}`; }
  if(item.type==="scene"&&data.entities[item.areaId]&&visible(data,data.entities[item.areaId]))specific=`<p><strong>Area:</strong> ${badges(data,[item.areaId])}</p>`;
  if(item.type==="affiliation"){const members=Object.values(data.entities).filter(i=>i.affiliationIds?.includes(item.id)&&visible(data,i));specific=members.length?`<section><h2>Members</h2>${badges(data,members.map(i=>i.id))}</section>`:"";}
  if(item.type==="area"){const children=entitiesOf(data,"area").filter(a=>a.parentAreaId===item.id&&visible(data,a));const scenes=entitiesOf(data,"scene").filter(scene=>{let id=scene.areaId,seen=new Set();while(id&&!seen.has(id)){if(id===item.id)return true;seen.add(id);id=data.entities[id]?.parentAreaId;}return false;}).filter(i=>visible(data,i));specific=`${item.parentAreaId&&visible(data,data.entities[item.parentAreaId])?`<p><strong>Within:</strong> ${badges(data,[item.parentAreaId])}</p>`:""}${children.length?`<section><h2>Areas</h2>${badges(data,children.map(i=>i.id))}</section>`:""}${scenes.length?`<section><h2>Scenes</h2>${badges(data,scenes.map(i=>i.id))}</section>`:""}`;}
  const source=item.source?.uuid?fromUuidSync(item.source.uuid):null;
  return `<article class="cw-article"><header>${image(item)?`<img src="${esc(image(item))}">`:""}<div><span>${LABELS[item.type]}</span><h1>${esc(item.name)}</h1></div></header>${specific}<div class="cw-description">${esc(item.description).replace(/\n/g,"<br>")}</div>${item.affiliationIds?.length?`<section><h2>Affiliations</h2>${badges(data,item.affiliationIds)}</section>`:""}${appearances.length?`<section><h2>Appearances</h2>${badges(data,appearances.map(i=>i.id))}</section>`:""}<footer>${source?button(item.type==="scene"?"Open Scene":"Open in Foundry","open-source",item.id,"fa-external-link-alt"):""}${game.user.isGM?button("Edit","edit",item.id,"fa-edit")+button("Delete","delete",item.id,"fa-trash"):""}</footer></article>`;
}
function sessionHtml(data,item){const arc=data.entities[item.arcId];const linked=linkSynopsis(data,item,{player:!game.user.isGM});const families=ENTITY_TYPES.filter(t=>!["session","arc","affiliation"].includes(t)).map(t=>{const ids=expandedSessionMembers(data,item).filter(id=>data.entities[id]?.type===t&&visible(data,data.entities[id]));return ids.length?`<section><h2>${LABELS[t]}s</h2>${badges(data,ids)}</section>`:"";}).join("");return `<article class="cw-article cw-session"><header>${item.art?`<img src="${esc(item.art)}">`:""}<div><span>${item.playDate}</span><h1>${esc(item.name)}</h1>${arc&&visible(data,arc)?`<button class="cw-parent" data-action="open" data-id="${arc.id}">${esc(arc.name)}</button>`:""}</div></header><div class="cw-synopsis">${linked.html}</div>${families}<footer>${game.user.isGM?button("Edit","edit",item.id,"fa-edit")+button("Delete","delete",item.id,"fa-trash"):""}</footer></article>`;}
function arcHtml(data,item){const dates=arcDates(data,item);const sessions=item.arcType==="arc"?arcSessions(data,item.id).filter(i=>visible(data,i)):[];const children=item.arcType==="metaplot"?metaplotArcs(data,item.id).filter(i=>visible(data,i)):[];const inherited=inheritedMembers(data,item).filter(id=>visible(data,data.entities[id]));return `<article class="cw-article cw-arc"><header>${item.art?`<img src="${esc(item.art)}">`:""}<div><span>${item.arcType==="metaplot"?"Metaplot":"Arc"}</span><h1>${esc(item.name)}</h1><p>${dates?`${dates.start} - ${item.status==="in-progress"?"Present":dates.end}`:"No Sessions"} · ${item.status==="complete"?"Complete":"In Progress"}</p></div></header>${children.length?`<section><h2>Arcs</h2><div class="cw-cards">${cards(children)}</div></section>`:""}${sessions.length?`<section><h2>Sessions</h2><div class="cw-session-list">${sessions.map(s=>`<button data-action="open" data-id="${s.id}"><span>${s.playDate}</span><strong>${esc(s.name)}</strong></button>`).join("")}</div></section>`:""}${inherited.length?`<section><h2>Campaign Collection</h2>${badges(data,inherited)}</section>`:""}<footer>${game.user.isGM?button("Edit","edit",item.id,"fa-edit")+button("Delete","delete",item.id,"fa-trash"):""}</footer></article>`;}
function searchHtml(data,query){const results=search(data,query,{player:!game.user.isGM});return `<article class="cw-search"><h1>Search</h1><p>${results.length} result(s) for “${esc(query)}”</p>${results.map(r=>`<button data-action="open" data-id="${r.entity.id}"><strong>${esc(r.entity.name)}</strong><span>${LABELS[r.entity.type]}${r.match==="alias"?` · alias: ${esc(r.alias)}`:r.match==="synopsis"?" · synopsis":""}</span></button>`).join("")||'<p class="cw-empty">Nothing found.</p>'}</article>`;}

class CampaignWikiApp extends Application {
  constructor(options={}){super(options);this.currentId=null;this.query="";this.openNavigation=new Set();}
  static get defaultOptions(){return foundry.utils.mergeObject(super.defaultOptions,{id:"campaign-wiki-app",title:"Campaign Wiki",width:1100,height:760,resizable:true,popOut:true,classes:["campaign-wiki"]});}
  async _renderInner(){const data=database();const content=this.query?searchHtml(data,this.query):this.currentId?articleHtml(data,data.entities[this.currentId]):homeHtml(data);return $(`<div class="cw-shell"><aside>${navHtml(data,this.openNavigation)}</aside><main><div class="cw-toolbar"><form data-search><input name="query" placeholder="Search Campaign Wiki" value="${esc(this.query)}"><button><i class="fas fa-search"></i></button></form>${game.user.isGM?button("New Arc","new-arc","","fa-plus")+button("New Session","new-session","","fa-plus"):""}</div><div class="cw-content">${content}</div></main></div>`);}
  activateListeners(html){super.activateListeners(html);html.on("click","[data-action]",event=>this.action(event));html.find("details[data-nav-key]").each((_index,details)=>details.addEventListener("toggle",()=>{const key=details.dataset.navKey;if(details.open)this.openNavigation.add(key);else this.openNavigation.delete(key);}));html.on("submit","[data-search]",event=>{event.preventDefault();this.query=new FormData(event.currentTarget).get("query");this.currentId=null;this.render(false);});}
  async action(event){event.preventDefault();const el=event.currentTarget,{action,id,type}=el.dataset;if(action==="home"){this.currentId=null;this.query="";return this.render(false);}if(action==="open"){this.currentId=id;this.query="";return this.render(false);}if(action==="new-session")return editSession();if(action==="new-arc")return editArc();if(action==="new")return type==="arc"?editArc():editArticle(null,type);if(action==="edit")return editEntity(id);if(action==="delete")return deleteArticle(id);if(action==="open-source")return fromUuidSync(database().entities[id]?.source?.uuid)?.sheet?.render(true);if(action==="resolve-attention"){const data=database();data.resolutions[id]={action:"ignored",at:new Date().toISOString()};return persist(data);}if(action==="accept-history")return acceptHistory(id);if(action==="resolve-link")return resolveLink(id);}
}

async function formDialog(title,content,{width=620,onRender}={}){return new Promise(resolve=>new Dialog({title,content:`<form class="cw-form">${content}</form>`,buttons:{save:{icon:'<i class="fas fa-save"></i>',label:"Save",callback:html=>resolve(new FormData(html.find("form")[0]))},cancel:{label:"Cancel",callback:()=>resolve(null)}},default:"save",close:()=>resolve(null),render:html=>{html.on("click","[data-file]",event=>new FilePicker({type:"image",callback:path=>html.find(`[name=${event.currentTarget.dataset.file}]`).val(path)}).render(true));onRender?.(html);}}, {width,classes:["dialog","campaign-wiki-dialog"]}).render(true));}
function formValues(form){const data=Object.fromEntries(form.entries());data.aliases=String(data.aliases??"").split(/\r?\n/).map(v=>v.trim()).filter(Boolean);data.affiliationIds=form.getAll("affiliationIds");return data;}
function affiliationPicker(data,item){const affiliations=entitiesOf(data,"affiliation").sort(alpha);if(!affiliations.length)return'<fieldset class="cw-affiliation-picker"><legend>Affiliations</legend><p class="cw-empty">No Affiliations yet. Create one under People → Affiliations.</p></fieldset>';return `<fieldset class="cw-affiliation-picker"><legend>Affiliations</legend><input type="search" data-affiliation-filter placeholder="Filter affiliations"><div>${affiliations.map(a=>`<label data-affiliation-name="${esc(a.name.toLowerCase())}"><input type="checkbox" name="affiliationIds" value="${a.id}"${item.affiliationIds?.includes(a.id)?" checked":""}><span>${esc(a.name)}</span></label>`).join("")}</div></fieldset>`;}
function commonFields(data,item){return `<label>Name<input name="name" required value="${esc(item.name)}"></label>${fileField("art",image(item),"Art")}<label>Description<textarea name="description" rows="8">${esc(item.description)}</textarea></label><label>Aliases <small>one per line</small><textarea name="aliases" rows="3">${esc((item.aliases??[]).join("\n"))}</textarea></label><label>Visibility<select name="visibility">${option(VISIBILITY.AUTOMATIC,"Automatic",item.visibility===VISIBILITY.AUTOMATIC)}${option(VISIBILITY.PUBLIC,"Always Public",item.visibility===VISIBILITY.PUBLIC)}${option(VISIBILITY.GM,"Always GM Only",item.visibility===VISIBILITY.GM)}</select></label>${affiliationPicker(data,item)}`;}
async function editEntity(id){const item=database().entities[id];if(!item)return;if(item.type==="session")return editSession(item);if(item.type==="arc")return editArc(item);return editArticle(item,item.type);}
async function editArticle(existing,type){let data=database();const item=existing??{id:makeId(type),type,name:"",description:"",art:"",aliases:[],visibility:VISIBILITY.AUTOMATIC,affiliationIds:[]};let extra="";
  if(type==="actor")extra=`<label>Classification<select name="classification">${["hero","villain","npc"].map(v=>option(v,v[0].toUpperCase()+v.slice(1),item.classification===v)).join("")}</select></label><label>Quote<textarea name="quote">${esc(item.quote)}</textarea></label>${fileField("tokenArt",item.tokenArt,"Token Art")}<label>DNPC of<select name="dnpcOwnerId">${option("","None",!item.dnpcOwnerId)}${entitiesOf(data,"actor").filter(a=>a.id!==item.id).map(a=>option(a.id,a.name,item.dnpcOwnerId===a.id)).join("")}</select></label>`;
  if(type==="scene")extra=`<label>Area<select name="areaId">${option("","None",!item.areaId)}${entitiesOf(data,"area").map(a=>option(a.id,a.name,item.areaId===a.id)).join("")}</select></label>`;
  if(type==="image")extra=`<label>Classification<select name="classification">${["vehicle","equipment","macguffin","media","other"].map(v=>option(v,v[0].toUpperCase()+v.slice(1),item.classification===v)).join("")}</select></label>`;
  if(type==="area")extra=`<label>Area Type<select name="areaType">${option("","Choose…",!item.areaType)}${option("city","City",item.areaType==="city")}${option("district","District",item.areaType==="district")}</select></label><label>Parent Area<select name="parentAreaId">${option("","None",!item.parentAreaId)}${entitiesOf(data,"area").filter(a=>a.id!==item.id).map(a=>option(a.id,a.name,item.parentAreaId===a.id)).join("")}</select></label>`;
  const form=await formDialog(`${existing?"Edit":"New"} ${LABELS[type]}`,commonFields(data,item)+extra,{onRender:html=>html.on("input","[data-affiliation-filter]",event=>{const query=event.currentTarget.value.trim().toLowerCase();html.find("[data-affiliation-name]").each((_i,row)=>row.hidden=query&&!row.dataset.affiliationName.includes(query));})});if(!form)return;const values=formValues(form);if(type==="actor")values.portrait=values.art;const saved=putEntity(data,{...item,...values,incomplete:false});await persist(data);app.currentId=saved.id;
}
async function editArc(existing,type="arc"){let data=database();const item=existing??{id:makeId("arc"),type:"arc",arcType:type,status:"in-progress",name:"",art:"",visibility:VISIBILITY.AUTOMATIC};const form=await formDialog(`${existing?"Edit":"New"} Arc`,`<label>Title<input name="name" required value="${esc(item.name)}"></label>${fileField("art",item.art,"Art")}<label>Type<select name="arcType">${option("arc","Arc",item.arcType==="arc")}${option("metaplot","Metaplot",item.arcType==="metaplot")}</select></label><label>Status<select name="status">${option("in-progress","In Progress",item.status==="in-progress")}${option("complete","Complete",item.status==="complete")}</select></label><label>Metaplot<select name="metaplotId">${option("","Standalone",!item.metaplotId)}${entitiesOf(data,"arc").filter(a=>a.arcType==="metaplot"&&a.id!==item.id).map(a=>option(a.id,a.name,item.metaplotId===a.id)).join("")}</select></label>`);if(!form)return;const values=Object.fromEntries(form.entries());
  if(existing&&existing.status!==values.status){if(values.status==="complete"){const impact=publicationImpact(data,item.id);if(!await confirmAction("Complete Arc?",`Publish ${impact.publish} Automatic article(s); ${impact.gmOnly} Always GM Only article(s) remain private?`))return;}else{const keep=await reopenChoice(item);if(keep===null)return;values.keepPublished=keep;}}
  if(values.arcType==="metaplot")values.metaplotId=null;const saved=putEntity(data,{...item,...values});await persist(data);app.currentId=saved.id;
}
async function editSession(existing){let data=database();const item=existing??{id:makeId("session"),type:"session",name:"",arcId:"",playDate:today(),art:"",synopsis:"",memberIds:[],visibility:VISIBILITY.AUTOMATIC};const familyOptions=type=>{const wiki=entitiesOf(data,type).map(a=>option(a.id,a.name,item.memberIds.includes(a.id)));if(!["actor","scene"].includes(type))return wiki.join("");const docs=type==="actor"?game.actors:game.scenes;const represented=new Set(entitiesOf(data,type).map(a=>a.source?.uuid).filter(Boolean));const foundry=[...docs].filter(doc=>!represented.has(doc.uuid)).map(doc=>option(`source:${type}:${doc.id}`,`${doc.name} — Foundry ${LABELS[type]}`));return [...wiki,...foundry].join("");};const families=["actor","scene","image"].map(type=>`<details class="cw-session-family"><summary>Featured ${LABELS[type]}s</summary><select name="memberIds" multiple data-family="${type}">${familyOptions(type)}</select><div class="cw-inline-create"><input data-new="${type}" placeholder="Create ${LABELS[type]} by name"><button type="button" data-create="${type}">Create & add</button></div></details>`).join("");
  const form=await formDialog(`${existing?"Edit":"New"} Session`,`<label>Session Title<input name="name" required value="${esc(item.name)}"></label><label>Arc<div class="cw-file"><select name="arcId" required>${option("","Choose an Arc…",!item.arcId)}${entitiesOf(data,"arc").filter(a=>a.arcType==="arc").map(a=>option(a.id,a.name,item.arcId===a.id)).join("")}</select><button type="button" data-inline-arc>+ New Arc</button></div></label><label>Play Date<input type="date" name="playDate" required value="${item.playDate}"></label>${fileField("art",item.art,"Session Art")}<label>Synopsis<textarea name="synopsis" rows="12">${esc(item.synopsis)}</textarea></label>${families}`,{width:760,onRender:html=>{html.on("click","[data-inline-arc]",async()=>{const before=new Set(entitiesOf(database(),"arc").map(a=>a.id));await editArc();const arc=entitiesOf(database(),"arc").find(a=>!before.has(a.id));if(arc)html.find("[name=arcId]").append(option(arc.id,arc.name,true));});html.on("click","[data-create]",async event=>{const type=event.currentTarget.dataset.create,input=html.find(`[data-new=${type}]`),name=input.val().trim();if(!name)return;const stub=await createStub(type,name);html.find(`[data-family=${type}]`).append(option(stub.id,stub.name,true));input.val("");});}});if(!form)return;data=database();const values=Object.fromEntries(form.entries()),members=[];for(const value of form.getAll("memberIds")){if(!value.startsWith("source:")){members.push(value);continue;}const [,type,id]=value.split(":"),created=await importFoundry(type,id);if(created)members.push(created.id);}data=database();values.memberIds=[...new Set(members)];const saved=putEntity(data,{...item,...values});await persist(data);app.currentId=saved.id;
}
async function createStub(type,name){const data=database();let source=null,item={id:makeId(type),type,name,visibility:VISIBILITY.AUTOMATIC,aliases:[],affiliationIds:[],incomplete:true};if(type==="actor"){const doc=await Actor.create({name,type:"character"});source={uuid:doc.uuid,id:doc.id,missing:false};Object.assign(item,{source,classification:"npc",portrait:doc.img,art:doc.img,tokenArt:doc.prototypeToken?.texture?.src||""});}else if(type==="scene"){const doc=await Scene.create({name});source={uuid:doc.uuid,id:doc.id,missing:false};Object.assign(item,{source});}const saved=putEntity(data,item);await persist(data);return saved;}
async function importFoundry(type,document){const data=database(),collection=type==="actor"?game.actors:game.scenes,doc=typeof document==="string"?collection.get(document):document;if(!doc)return null;const existing=Object.values(data.entities).find(i=>i.type===type&&i.source?.uuid===doc.uuid);if(existing)return existing;const description=type==="actor"?String(doc.system?.description?.value||doc.system?.background||"").replace(/<[^>]+>/g,""):"";const saved=putEntity(data,{id:makeId(type),type,name:doc.name,description,source:{uuid:doc.uuid,id:doc.id,missing:false},art:type==="actor"?doc.img:(doc.background?.src||""),portrait:doc.img,tokenArt:doc.prototypeToken?.texture?.src||"",quote:String(doc.system?.quote||""),classification:"npc",visibility:VISIBILITY.AUTOMATIC,aliases:[],affiliationIds:[]});await persist(data);return saved;}

async function deleteArticle(id){const data=database(),item=data.entities[id];if(!item)return;const warning=item.type==="arc"&&item.arcType==="arc"?`This also deletes ${arcSessions(data,id).length} Session(s). Associated articles and Foundry documents survive.`:item.type==="arc"?"Child Arcs become standalone; their Sessions survive.":"The underlying Foundry Actor or Scene will not be deleted.";if(!await confirmAction(`Delete ${item.name}?`,warning))return;removeEntity(data,id);await persist(data);app.currentId=null;}
function confirmAction(title,content){return new Promise(resolve=>new Dialog({title,content:`<p>${esc(content)}</p>`,buttons:{yes:{label:"Confirm",callback:()=>resolve(true)},no:{label:"Cancel",callback:()=>resolve(false)}},default:"no",close:()=>resolve(false)}).render(true));}
function reopenChoice(item){return new Promise(resolve=>new Dialog({title:`Reopen ${item.name}?`,content:"<p>Choose how existing publication should be handled.</p>",buttons:{keep:{label:"Keep Published",callback:()=>resolve(true)},revert:{label:"Revert Publication",callback:()=>resolve(false)},cancel:{label:"Cancel",callback:()=>resolve(null)}},default:"cancel",close:()=>resolve(null)}).render(true));}
async function acceptHistory(id){const parts=id.split(":"),entityId=parts[1],sessionId=parts[2],data=database(),session=data.entities[sessionId];if(!session)return;session.memberIds=[...new Set([...session.memberIds,entityId])];data.resolutions[id]={action:"added",at:new Date().toISOString()};await persist(data);}
async function resolveLink(id){const data=database(),attention=deriveAttention(data).find(a=>a.id===id);if(!attention)return;const form=await formDialog("Resolve Synopsis Link",`<p>Choose the target for “${esc(attention.text)}”.</p><label>Target<select name="target">${attention.candidates.map(cid=>option(cid,data.entities[cid]?.name)).join("")}${option("unlinked","Leave Unlinked")}</select></label>`);if(!form)return;data.entities[attention.entityId].synopsisDecisions[attention.key]=form.get("target");data.resolutions[id]={action:form.get("target"),at:new Date().toISOString()};await persist(data);}

function saveBlob(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportPackage(){const payload={format:"campaign-wiki-package",version:1,exportedAt:new Date().toISOString(),database:database(),assets:[]};saveBlob(JSON.stringify(payload,null,2),"application/json",`${slug(game.world.title)}-campaign-wiki-${today()}.json`);}
function importPackage(){new FilePicker({type:"json",callback:async path=>{try{const payload=await(await fetch(path)).json(),incoming=payload.database??payload,errors=validateDatabase(incoming);if(!incoming.entities)throw new Error("Not a Campaign Wiki package.");if(errors.length)throw new Error(errors.join("\n"));exportPackage();await persist(incoming);ui.notifications.info("Campaign Wiki replaced after automatic backup.");}catch(error){console.error(error);ui.notifications.error(error.message);}}}).render(true);}

function analyzeLegacy(overlay){const records=Object.entries(overlay?.articles??{});return{records,actors:records.filter(([id])=>id.startsWith("Actor.")).length,sessions:records.filter(([,v])=>v.arcId&&v.sessionDate).length,arcs:records.filter(([,v])=>v.categoryId==="arcs"&&!v.arcId).length};}
async function offerMigration(){const current=database();if(Object.keys(current.entities).length||current.migration)return;let overlay;try{overlay=game.settings.get(MODULE_ID,SETTING_LEGACY_OVERLAY);}catch{return;}if(!overlay?.articles||!Object.keys(overlay.articles).length)return;const report=analyzeLegacy(overlay);if(!await confirmAction("Campaign Wiki redesign migration",`Found ${report.records.length} legacy records (${report.actors} Actors, ${report.arcs} possible Arcs, ${report.sessions} Sessions). Download a backup and migrate now?`))return;exportPackage();await migrateLegacy(overlay);}
function legacySource(uuid){const doc=fromUuidSync(uuid);return doc?{name:doc.name,img:uuid.startsWith("Scene.")?(doc.background?.src||doc.img||""):doc.img,tokenArt:doc.prototypeToken?.texture?.src||""}:null;}
async function migrateLegacy(overlay){const result=recoverLegacy(emptyDatabase(game.world.id),overlay,{sourceDocument:legacySource});result.database.migration.source="legacy-overlay";result.database.migration.at=new Date().toISOString();await persist(result.database);ui.notifications.info(`Migration recovered ${result.stats.enriched} records, created ${result.stats.created}, and restored ${result.stats.sessionsLinked} Session memberships.`);}

function legacyOverlay(){try{return game.settings.get(MODULE_ID,SETTING_LEGACY_OVERLAY);}catch{return null;}}
async function repairLegacy(overlay=legacyOverlay()){
  if(!overlay?.articles||!Object.keys(overlay.articles).length){ui.notifications.warn("No preserved legacy overlay was found in this world. Use the backup-file recovery option.");return;}
  exportPackage();const result=recoverLegacy(database(),overlay,{sourceDocument:legacySource});await persist(result.database);const s=result.stats;ui.notifications.info(`Campaign Wiki recovered: ${s.enriched} enriched, ${s.created} created, ${s.sessionsLinked} Session links, ${s.affiliationsCreated} Affiliations, ${s.dnpcsLinked} DNPC links.`);return result;
}
async function offerRepair(){const data=database(),overlay=legacyOverlay();if(!Object.keys(data.entities).length||(data.migration?.repairVersion??0)>=2||!overlay?.articles||!Object.keys(overlay.articles).length)return;const report=analyzeLegacy(overlay);if(await confirmAction("Finish rescuing Campaign Wiki?",`Your preserved legacy data contains ${report.records.length} records. This repair corrects Affiliation assignments, rebuilds the conceptual navigation, and rechecks the imported campaign structure. A v2 backup downloads first. Run recovery?`))await repairLegacy(overlay);}
function repairFromFile(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=async()=>{try{const payload=JSON.parse(await input.files[0].text()),overlay=payload.overlay??payload;if(!overlay?.articles)throw new Error("This file does not contain a Campaign Wiki legacy overlay.");await repairLegacy(overlay);}catch(error){console.error(error);ui.notifications.error(error.message);}};input.click();}

function objectStrings(value,output=[]){if(typeof value==="string")output.push(value.trim());else if(Array.isArray(value))for(const item of value)objectStrings(item,output);else if(value&&typeof value==="object")for(const item of Object.values(value))objectStrings(item,output);return output.filter(Boolean);}
function inferDnpcLinks(data){let changed=false;const wikiActors=entitiesOf(data,"actor"),bySourceId=new Map(wikiActors.flatMap(actor=>actor.source?[ [actor.source.id,actor],[actor.source.uuid,actor] ]:[]));for(const owner of wikiActors){const doc=owner.source?.uuid?fromUuidSync(owner.source.uuid):null;if(!doc)continue;const dependentItems=[...(doc.items??[])].filter(item=>/DEPENDENTNPC|\bDNPC\b/i.test(JSON.stringify(item.toObject?.()??item)));if(!dependentItems.length){if(owner.dnpcAmbiguous){owner.dnpcAmbiguous=false;changed=true;}continue;}const candidates=new Set();for(const dependent of dependentItems){for(const value of objectStrings(dependent.toObject?.()??dependent)){const direct=bySourceId.get(value);if(direct&&direct.id!==owner.id)candidates.add(direct.id);const normalized=value.toLocaleLowerCase();for(const actor of wikiActors)if(actor.id!==owner.id&&[actor.name,...(actor.aliases??[])].some(name=>name.toLocaleLowerCase()===normalized))candidates.add(actor.id);}}if(candidates.size===1){const target=data.entities[[...candidates][0]];if(target.dnpcOwnerId!==owner.id){target.dnpcOwnerId=owner.id;changed=true;}if(owner.dnpcAmbiguous){owner.dnpcAmbiguous=false;changed=true;}}else if(owner.dnpcAmbiguous!==true){owner.dnpcAmbiguous=true;changed=true;}}return changed;}
async function syncSources(){if(!game.user.isGM)return;const data=database();let changed=false;for(const item of Object.values(data.entities)){if(!["actor","scene"].includes(item.type)||!item.source)continue;const doc=fromUuidSync(item.source.uuid);if(!doc){if(!item.source.missing){item.source.missing=true;changed=true;}continue;}if(item.source.missing){item.source.missing=false;changed=true;}if(doc.name!==item.name){item.aliases=[...new Set([...(item.aliases??[]),item.name])];item.name=doc.name;changed=true;}const art=item.type==="actor"?doc.img:(doc.background?.src||doc.img||"");if(item.art!==art){item.art=art;if(item.type==="actor")item.portrait=art;changed=true;}if(item.type==="actor"){const token=doc.prototypeToken?.texture?.src||"";if(item.tokenArt!==token){item.tokenArt=token;changed=true;}}}changed=inferDnpcLinks(data)||changed;if(changed)await persist(data);}
function installLauncher(){
  let launcher=document.querySelector("#campaign-wiki-launcher");
  if(!launcher){launcher=document.createElement("button");launcher.id="campaign-wiki-launcher";launcher.type="button";launcher.dataset.tooltip="Open Campaign Wiki";launcher.setAttribute("aria-label","Open Campaign Wiki");launcher.innerHTML='<i class="fas fa-book-open"></i><span>Campaign Wiki</span>';launcher.addEventListener("click",openWiki);document.body.append(launcher);}
  positionLauncher();
}
function positionLauncher(){const launcher=document.querySelector("#campaign-wiki-launcher");if(!launcher)return;const players=document.querySelector("#players");const rect=players?.getBoundingClientRect();launcher.style.left=rect&&rect.right>0?`${Math.round(rect.right+10)}px`:"228px";launcher.style.bottom=rect&&rect.bottom>0?`${Math.max(8,Math.round(window.innerHeight-rect.bottom))}px`:"12px";}
function openWiki(){app??=new CampaignWikiApp();app.currentId=null;app.query="";app.openNavigation.clear();app.render(true);}
class OpenWikiMenu extends FormApplication{render(){openWiki();return this;}}
class ExportWikiMenu extends FormApplication{render(){exportPackage();return this;}}
class ImportWikiMenu extends FormApplication{render(){importPackage();return this;}}
class RepairWikiMenu extends FormApplication{render(){const overlay=legacyOverlay();new Dialog({title:"Recover Legacy Campaign Wiki",content:`<p>Re-read the preserved legacy overlay and merge its writing, art, classifications, Affiliations, DNPC ownership, Arcs, Sessions, and featured-content links into v2. Existing v2 records are enriched in place; Foundry Actors and Scenes are not duplicated. A v2 backup downloads first.</p>${overlay?.articles?"<p><strong>A preserved world overlay was found.</strong></p>":"<p>No world overlay was detected. Choose your legacy Campaign Wiki JSON backup.</p>"}`,buttons:{world:{label:"Recover Preserved Data",callback:()=>repairLegacy(overlay)},file:{label:"Choose Backup File",callback:repairFromFile},cancel:{label:"Cancel"}},default:overlay?.articles?"world":"file"}).render(true);return this;}}

Hooks.once("init",()=>{
  game.settings.register(MODULE_ID,SETTING_DATABASE,{scope:"world",config:false,type:Object,default:emptyDatabase()});
  game.settings.register(MODULE_ID,SETTING_LEGACY_OVERLAY,{scope:"world",config:false,type:Object,default:{}});
  game.settings.registerMenu(MODULE_ID,"openWiki",{name:"Open Campaign Wiki",label:"Open",hint:"Open Campaign Wiki on Home.",icon:"fas fa-book-open",type:OpenWikiMenu,restricted:false});
  game.settings.registerMenu(MODULE_ID,"exportWiki",{name:"Export Campaign Wiki",label:"Export",hint:"Download the world-specific Campaign Wiki package.",icon:"fas fa-download",type:ExportWikiMenu,restricted:true});
  game.settings.registerMenu(MODULE_ID,"importWiki",{name:"Import Campaign Wiki",label:"Import",hint:"Back up and replace this world's Campaign Wiki.",icon:"fas fa-upload",type:ImportWikiMenu,restricted:true});
  game.settings.registerMenu(MODULE_ID,"repairWiki",{name:"Recover Legacy Campaign Wiki",label:"Recover",hint:"Repair a v2 migration from the preserved world overlay or a legacy JSON backup without duplicating Foundry documents.",icon:"fas fa-life-ring",type:RepairWikiMenu,restricted:true});
  game.modules.get(MODULE_ID).api={open:openWiki,getDatabase:database,put:async input=>{const data=database(),result=putEntity(data,input);await persist(data);return result;},remove:async id=>{const data=database();removeEntity(data,id);await persist(data);},importFoundry,export:exportPackage};
});
Hooks.once("ready",async()=>{ui.campaignWiki={open:openWiki,render:openWiki,recover:repairLegacy};installLauncher();window.addEventListener("resize",positionLauncher);await syncSources();if(game.user.isGM){await offerMigration();await offerRepair();}});
Hooks.on("renderSidebar",installLauncher);Hooks.on("collapseSidebar",()=>setTimeout(positionLauncher,100));
Hooks.on("updateActor",syncSources);Hooks.on("updateScene",syncSources);Hooks.on("deleteActor",syncSources);Hooks.on("deleteScene",syncSources);
