import {validateBatch,planBatch,uploadBatch,manualPage,reviewFingerprint,reviewState,moveReference} from './rulebook-import.js';
import {escapeHtml as esc,refKey,effectivePage,searchRules,safeImagePath,validateBook,sectionHtml,continuationChain} from './rulebook-core.js';
const M='campaign-wiki';let adapter,reader;const cache=new Map();
const settings=key=>game.settings.get(M,key);
const base=()=>String(settings('rulebookBase')).replace(/\/+$/,'');
const edits=()=>settings('rulebookEdits')?.[reader?.book?.id]||{};
const imageURL=src=>/^https?:\/\//i.test(src)||src.startsWith('modules/')||src.startsWith('worlds/')||src.startsWith('/')?src:`${base()}/${src}`;
async function json(path){const response=await fetch(/^https?:\/\//i.test(path)||path.startsWith('/')?path:`${base()}/${path}`);if(!response.ok)throw new Error(`Rulebook file unavailable (${response.status}). Check the Rulebook Content Folder setting.`);return response.json();}
async function getPage(id){if(!reader.book.pages.some(p=>p.id===id))throw new Error('Unknown rulebook page.');const key=base()+'/'+id;if(!cache.has(key)){const page=await json(reader.book.pages.find(p=>p.id===id)?.file||`pages/${id}.json`);if(page.id!==id||!Array.isArray(page.sections))throw new Error('Invalid rulebook page.');const file=reader.book.pages.find(p=>p.id===id)?.file||`${base()}/pages/${id}.json`;if(file)for(const section of page.sections)for(const image of section.images||[])if(!/^(https?:|\/|modules\/|worlds\/)/i.test(image.src))image.src=new URL(image.src,new URL('../',new URL(file,window.location.href))).href;if(cache.size>=12)cache.delete(cache.keys().next().value);cache.set(key,page);}return cache.get(key);}
const btn=(label,action,ref={})=>`<button type="button" data-rb="${action}" data-page="${esc(ref.pageId||'')}" data-section="${esc(ref.sectionId||'')}">${esc(label)}</button>`;
function form(title,content){return new Promise(resolve=>new Dialog({title,content:`<form class="rb-editor">${content}</form>`,buttons:{save:{label:'Save',callback:html=>resolve(new FormData(html.find('form')[0]))},cancel:{label:'Cancel',callback:()=>resolve(null)}},default:'save',render:html=>{html.on('click','[data-rb-file]',event=>{event.preventDefault();const input=html.find(`[name="${event.currentTarget.dataset.rbFile}"]`);new FilePicker({type:'image',current:input.val(),callback:path=>input.val(new URL(path,window.location.href).href)}).render(true);});},close:()=>resolve(null)},{width:720}).render(true));}
async function saveEdit(sectionId,value){if(!game.user.isGM)throw new Error('Only the GM may edit rulebook content.');const all=foundry.utils.deepClone(settings('rulebookEdits'));all[reader.book.id]??={};all[reader.book.id][sectionId]={...(all[reader.book.id][sectionId]||{}),...value};await game.settings.set(M,'rulebookEdits',all);}
function controls(page,section){const ref={pageId:page.id,sectionId:section?.id},favorites=game.user.getFlag(M,'rulebookFavorites')?.[reader.book.id]||[];return btn(favorites.some(f=>refKey(f)===refKey(ref))?'★ Saved':'☆ Favorite','favorite',ref)+btn('Collect','collect',ref)+(game.user.isGM?btn('Show players','show',ref)+(section?btn('Edit section','edit',ref)+btn('Images','images',ref)+btn('House rule','house',ref):btn('Add section','add-section',ref)):'');}
function continuationControls(page,section){const chain=continuationChain(effectiveTOC(),{pageId:page.id,sectionId:section.id});if(chain.length<2)return '';const i=chain.findIndex(r=>r.sectionId===section.id);return (i?btn('Continued from previous page','page',chain[i-1]):'')+(i<chain.length-1?btn('Continues on next page','page',chain[i+1]):'')+btn('Read complete rule','complete-rule',{pageId:page.id,sectionId:section.id});}
function renderSection(page,section,{includeHouseRule=true}={}){return sectionHtml({...section,houseRule:includeHouseRule?section.houseRule:''},{linkText:adapter.linkText,imageURL,controls:controls(page,section)+continuationControls(page,section)});}
const absoluteAsset=src=>new URL(imageURL(src),window.location.href).href;
const removedPages=()=>new Set(settings('rulebookRemovedPages')?.[reader.book.id]||[]);
const activePage=id=>reader.book.pages.some(p=>p.id===id)&&!removedPages().has(id);
const activePages=()=>reader.book.pages.filter(p=>activePage(p.id));
async function managePages(){
 const removed=removedPages(),data=await form('Manage rulebook pages',`<p>Check pages to keep. Unchecked pages disappear from search, contents, glossary and favorites for everyone. Source files and notes are retained for restoration here. Printed page numbers do not change.</p><div class="rb-page-options">${reader.book.pages.map(p=>`<label class="rb-page-option"><input type="checkbox" name="keep" value="${esc(p.id)}" ${removed.has(p.id)?'':'checked'}><span>Page ${esc(p.label)}: ${esc(p.title||p.id)}</span></label>`).join('')}</div>`);
 if(!data)return;const keep=new Set(data.getAll('keep')),all=foundry.utils.deepClone(settings('rulebookRemovedPages')||{});all[reader.book.id]=reader.book.pages.filter(p=>!keep.has(p.id)).map(p=>p.id);await game.settings.set(M,'rulebookRemovedPages',all);reader.render(false);
}
const effectiveTOC=()=>reader.book.toc.filter(row=>activePage(row.pageId)).map(row=>Object.hasOwn(edits()[row.sectionId]||{},'continuesFrom')?{...row,continuesFrom:edits()[row.sectionId].continuesFrom}:row);
const reviewFor=page=>reviewState(page,settings('rulebookReviews')?.[reader.book.id]?.[page.id]);
const reviewLabel=status=>({'needs-review':'Needs review',verified:'Verified',imported:'Imported'}[status]||'Needs review');
async function reviewPage(page){const state=reviewFor(page),data=await form(`Review page ${page.label}`,`<label>Status<select name="status">${['imported','needs-review','verified'].map(s=>`<option value="${s}" ${state.status===s?'selected':''}>${reviewLabel(s)}</option>`).join('')}</select></label><label>Review notes<textarea name="note" rows="5">${esc(state.note||'')}</textarea></label>`);if(!data)return;const all=foundry.utils.deepClone(settings('rulebookReviews')||{});all[reader.book.id]??={};all[reader.book.id][page.id]={status:String(data.get('status')),note:String(data.get('note')),fingerprint:reviewFingerprint(page),reviewedBy:game.user.id,reviewedAt:new Date().toISOString()};await game.settings.set(M,'rulebookReviews',all);reader.render(false);}
async function sourceSnapshot(){if(!reader.book)return {book:null,pages:[]};const book=structuredClone(reader.book),pages=[];for(const meta of book.pages){const page=structuredClone(await getPage(meta.id));meta.file=new URL(meta.file||`${base()}/pages/${meta.id}.json`,window.location.href).href;for(const s of page.sections)for(const im of s.images)im.src=absoluteAsset(im.src);pages.push(page);}return {book,pages};}
async function commitBatch(batch){
 if(!game.user.isGM)throw new Error('Only the GM may import pages.');if(reader.importing)throw new Error('An import is already running.');reader.importing=true;
 const previousBase=base();try{
  const current=await sourceSnapshot(),plan=planBatch(current.book,current.pages,validateBatch(batch));
  const destination=String(settings('rulebookUploadFolder')||'').replace(/^\/+|\/+$/g,'');if(destination.split('/').includes('..'))throw new Error('Choose a valid upload folder.');
  const folder=[destination,`rulebook-${Date.now()}-${foundry.utils.randomID(6)}`].filter(Boolean).join('/');
  const next=await uploadBatch(plan,batch.assets||[],{folder,createDirectory:path=>FilePicker.createDirectory('data',path),readJson:async path=>{const response=await fetch(path);if(!response.ok)throw new Error('Uploaded contents could not be read.');return response.json();},upload:async(path,name,payload)=>{let blob;if(payload.json)blob=new Blob([JSON.stringify(payload.json)],{type:'application/json'});else {const raw=atob(payload.data);blob=new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:payload.mime});}const result=await FilePicker.upload('data',path,new File([blob],name,{type:blob.type}),{}, {notify:false});return result?.path?new URL(result.path,window.location.href).href:null;},onProgress:(done,total)=>{if(done===1||done===total)ui.notifications.info(`Saving rulebook ${done}/${total} files…`);}});
  if(base()!==previousBase)throw new Error('The active book changed during import; the imported files were saved but not activated.');
  await game.settings.set(M,'rulebookPreviousBase',previousBase);await game.settings.set(M,'rulebookBase',next);reader.book=null;reader.index=null;cache.clear();ui.notifications.info(`${plan.added} page(s) added; ${plan.replaced} page(s) updated. Your notes and favorites were preserved.`);
 }finally{reader.importing=false;}
}
async function addManualPage(){
 const last=reader.book?.pages.at(-1),choices=(reader.book?.toc||[]).filter(r=>r.pageId===last?.id),nextLabel=last&&/^\d+$/.test(last.label)?String(Number(last.label)+1):'';
 const data=await form('Add rulebook page',`<p>Paste one printed page. Put <strong>## Heading</strong> on a line to begin a section. You can add images after saving.</p><label>Printed page number<input name="label" value="${esc(nextLabel)}" placeholder="11 or S3" required></label><label>Page title<input name="title" required></label><label>Reading order<input type="number" min="0" step="0.1" name="order" value="${(last?.order??last?.pdfPage??0)+1}"></label><label>The first section continues from<select name="continues"><option value="">A new section</option>${choices.map(r=>`<option value="${esc(refKey(r))}">Page ${esc(last.label)} — ${esc(r.title)}</option>`).join('')}</select></label><label>Page text<textarea name="text" rows="16" placeholder="## Section heading&#10;Paste the section text here.&#10;&#10;## Another heading&#10;More text…"></textarea></label>`);
 if(!data)return;const label=String(data.get('label')).trim();if(reader.book?.pages.some(p=>p.label===label))throw new Error('That printed page already exists. Open it and use Edit section to make corrections.');
 const page=manualPage({label,title:String(data.get('title')),text:String(data.get('text')),order:Number(data.get('order')),id:`page-${foundry.utils.randomID().toLowerCase()}`});const continuation=choices.find(r=>refKey(r)===data.get('continues'));if(continuation){page.sections[0].continuesFrom={pageId:continuation.pageId,sectionId:continuation.sectionId};page.sections[0].title=continuation.title;}
 const book={...(reader.book||{schemaVersion:1,id:'hero-rulebook',title:'HERO Rulebook',glossary:[]}),pages:[{id:page.id,label:page.label,title:page.title,order:page.order}],toc:page.sections.map((s,i)=>({pageId:page.id,sectionId:s.id,title:s.title,level:i?2:1,...(s.continuesFrom?{continuesFrom:s.continuesFrom}:{})})),glossary:[]};
 await commitBatch({format:'hero-rulebook-batch-v1',book,pages:[page],assets:[]});reader.pageId=page.id;reader.sectionId='';reader.mode='page';reader.render(false);
}
async function importBatchFile(){const data=await form('Import prepared pages','<p>Choose a prepared rulebook batch. Existing section IDs and your notes are preserved. To paste text yourself, use Add page.</p><input type="file" name="batch" accept=".json,application/json" required>');if(!data)return;const file=data.get('batch');if(!file?.size||file.size>50*1024*1024)throw new Error('Choose a batch JSON smaller than 50 MB.');const batch=validateBatch(JSON.parse(await file.text()));const current=await sourceSnapshot(),plan=planBatch(current.book,current.pages,batch);const confirmation=await form('Review import',`<p><strong>${esc(batch.book.title)}</strong></p><p>${plan.added} new page(s), ${plan.replaced} existing page(s) updated. ${batch.assets?.length||0} images. No pages will be removed.</p><p>Click Save to upload this batch and activate it after verification.</p>`);if(confirmation){await commitBatch(batch);reader.render(false);}}
function downloadJSON(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportNotes(){downloadJSON({format:'hero-rulebook-notes-v1',bookId:reader.book.id,edits:edits(),glossary:settings('rulebookGlossary')?.[reader.book.id]||[],reviews:settings('rulebookReviews')?.[reader.book.id]||{},favorites:game.user.getFlag(M,'rulebookFavorites')?.[reader.book.id]||[]},`${reader.book.id}-notes.json`);}

async function addSection(page){const data=await form(`Add section to page ${page.label}`,'<label>Heading<input name="title" required></label><label>Text<textarea name="text" rows="12"></textarea></label>');if(!data)return;const title=String(data.get('title')||'').trim(),text=String(data.get('text')||'').trim();if(!title||!text)throw new Error('Enter a heading and text.');const source=structuredClone(await getPage(page.id));source.sections.push({id:`${source.id}-s-${foundry.utils.randomID().toLowerCase()}`,title,text,images:[]});const book={...reader.book,pages:[{id:source.id,label:source.label,title:source.title,order:source.order,pdfPage:source.pdfPage}],toc:source.sections.map((s,i)=>({pageId:source.id,sectionId:s.id,title:s.title,level:i?2:1})),glossary:reader.book.glossary.filter(r=>r.pageId===source.id)};await commitBatch({format:'hero-rulebook-batch-v1',book,pages:[source],assets:[]});reader.pageId=source.id;reader.render(false);}
const glossaryTerms=()=>{const terms=new Map((reader.book.glossary||[]).map(t=>[t.term.toLocaleLowerCase(),t]));for(const term of settings('rulebookGlossary')?.[reader.book.id]||[])terms.set(term.term.toLocaleLowerCase(),term);return [...terms.values()].filter(t=>activePage(t.pageId));};
async function editGlossary(){const data=await form('Add or update glossary term',`<p>Entering an existing term updates its definition and reference.</p><label>Term<input name="term" required></label><label>Definition<textarea name="definition" rows="5"></textarea></label><label>Rule section<select name="ref">${effectiveTOC().map(r=>`<option value="${esc(refKey(r))}">Page ${esc(reader.book.pages.find(p=>p.id===r.pageId).label)} — ${esc(r.title)}</option>`).join('')}</select></label>`);if(!data)return;const term=String(data.get('term')||'').trim(),definition=String(data.get('definition')||'').trim(),ref=effectiveTOC().find(r=>refKey(r)===data.get('ref'));if(!term||!definition||!ref)throw new Error('Enter a term, definition and source section.');const all=foundry.utils.deepClone(settings('rulebookGlossary')||{}),entries=all[reader.book.id]||[];all[reader.book.id]=[...entries.filter(t=>t.term.toLocaleLowerCase()!==term.toLocaleLowerCase()),{term,definition,pageId:ref.pageId,sectionId:ref.sectionId}];await game.settings.set(M,'rulebookGlossary',all);reader.render(false);}
async function restoreNotes(){const data=await form('Restore rulebook notes','<p>Restore a notes export for this book. Entries in the file replace matching notes; other notes remain. Your personal favorites are merged.</p><input type="file" name="notes" accept=".json,application/json">');if(!data)return;const file=data.get('notes');if(!file?.size||file.size>10*1024*1024)throw new Error('Choose a notes JSON smaller than 10 MB.');const payload=JSON.parse(await file.text());if(payload.format!=='hero-rulebook-notes-v1'||payload.bookId!==reader.book.id)throw new Error('Choose a notes export for this book.');const sectionIds=new Set(reader.book.toc.map(r=>r.sectionId)),pageIds=new Set(reader.book.pages.map(p=>p.id)),incoming={};for(const [key,value] of Object.entries(payload.edits||{})){if(!sectionIds.has(key))continue;if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Invalid section notes.');const entry={};for(const field of ['title','text','houseRule'])if(Object.hasOwn(value,field)){if(typeof value[field]!=='string')throw new Error('Invalid text in notes.');entry[field]=value[field];}if(value.images){if(!Array.isArray(value.images)||value.images.some(im=>!safeImagePath(im.src)))throw new Error('Invalid image notes.');entry.images=value.images;}if(Object.hasOwn(value,'continuesFrom'))entry.continuesFrom=value.continuesFrom;incoming[key]=entry;}
 const prospective={...edits(),...incoming},snapshot=await sourceSnapshot(),pages=snapshot.pages.map(p=>effectivePage(p,prospective));for(const page of pages)for(const section of page.sections)for(const image of section.images)image.src=absoluteAsset(image.src);const verification={format:'hero-rulebook-batch-v1',book:snapshot.book,pages,assets:[]};planBatch(snapshot.book,snapshot.pages,verification);
 const all=foundry.utils.deepClone(settings('rulebookEdits')||{});all[reader.book.id]={...edits(),...incoming};await game.settings.set(M,'rulebookEdits',all);
 const reviews=foundry.utils.deepClone(settings('rulebookReviews')||{});reviews[reader.book.id]??={};for(const [id,value] of Object.entries(payload.reviews||{}))if(pageIds.has(id)&&['imported','needs-review','verified'].includes(value?.status))reviews[reader.book.id][id]=value;await game.settings.set(M,'rulebookReviews',reviews);
 const favorites=foundry.utils.deepClone(game.user.getFlag(M,'rulebookFavorites')||{}),merged=new Map((favorites[reader.book.id]||[]).map(r=>[refKey(r),r]));for(const ref of payload.favorites||[])if(pageIds.has(ref.pageId)&&(!ref.sectionId||sectionIds.has(ref.sectionId)))merged.set(refKey(ref),ref);favorites[reader.book.id]=[...merged.values()];await game.user.setFlag(M,'rulebookFavorites',favorites);
 const glossary=foundry.utils.deepClone(settings('rulebookGlossary')||{}),terms=new Map((glossary[reader.book.id]||[]).map(t=>[t.term.toLocaleLowerCase(),t]));for(const t of payload.glossary||[])if(typeof t.term==='string'&&typeof t.definition==='string'&&pageIds.has(t.pageId)&&sectionIds.has(t.sectionId))terms.set(t.term.toLocaleLowerCase(),t);glossary[reader.book.id]=[...terms.values()];await game.settings.set(M,'rulebookGlossary',glossary);ui.notifications.info('Rulebook notes restored.');reader.render(false);
}

class RulebookReader extends Application {
 static get defaultOptions(){return {...super.defaultOptions,id:'campaign-rulebook',title:'HERO Rulebook',width:1050,height:780,resizable:true,classes:['campaign-wiki','rulebook-reader']};}
 constructor(...args){super(...args);this.pageId='';this.sectionId='';this.mode='page';this.query='';this.includeHouseRules=true;this.collection=[];this.history=[];this.collectionArticle=null;}
 async _renderInner(){
  try{
   this.book??=validateBook(await json('book.json'));const pages=activePages();if(!this.pageId)this.pageId=pages[0]?.id||'';
   const favorites=(game.user.getFlag(M,'rulebookFavorites')?.[this.book.id]||[]).filter(r=>activePage(r.pageId));
   let body='';
   if(this.mode==='search'){
    this.index??=await json('search.json');const results=searchRules(this.index.filter(r=>activePage(r.pageId)),this.query,{overrides:edits(),includeHouseRules:this.includeHouseRules});body=`<h1>Search results</h1><p>${results.length} matching sections</p>${results.map(row=>`<article class="rb-result">${btn(`${row.title} · p. ${row.label}`,row.continued?'complete-rule':'page',row)}<p>${esc(row.snippet)}</p></article>`).join('')}`;
   }else if(this.mode==='review'){
    body='<h1>Page review</h1><p>Verification applies to the current text and images. Changes return a page to Needs review.</p>';for(const meta of pages){const page=effectivePage(await getPage(meta.id),edits()),state=reviewFor(page);body+=`<article class="rb-result">${btn(`Page ${meta.label}: ${meta.title}`,'page',{pageId:meta.id})}<strong> ${reviewLabel(state.status)}</strong>${game.user.isGM?btn('Review status','review-page',{pageId:meta.id}):''}<p>${esc(state.note||'')}</p></article>`;}
   }else if(this.mode==='glossary')body=`<h1>Glossary</h1>${game.user.isGM?btn('Add / update term','glossary-edit'):''}<p>${esc(this.book.glossaryNote)}</p><input data-glossary-filter placeholder="Filter glossary" aria-label="Filter glossary">${glossaryTerms().sort((a,b)=>a.term.localeCompare(b.term)).map(term=>`<article data-term="${esc(term.term.toLowerCase())}"><h2>${btn(term.term,'page',term)}</h2><p>${esc(term.definition)}</p></article>`).join('')}`;
   else if(this.mode==='favorites')body=`<h1>My favorites</h1>${favorites.length?favorites.map(ref=>`<article>${btn(ref.label,'page',ref)}${btn('Remove','favorite',ref)}</article>`).join(''):'<p>Favorite any page or section to keep it here.</p>'}`;
   else if(this.mode==='collection'||this.mode==='rule'){
    body=this.mode==='rule'?'<h1>Complete rule</h1><p>Connected passages in printed-page order. Use Collect to add a passage to your reference article.</p>':`<h1>Collected rules</h1><p>Linked source sections; house rules appear only when explicitly included.</p>${btn(this.collectionArticle?'Update wiki article':'Save as wiki article','save-collection')}${btn('Start new collection','new-collection')}`;
    for(const ref of this.mode==='rule'?this.ruleRefs:this.collection){if(!activePage(ref.pageId)){body+=`<p>Source page removed or unavailable. ${this.mode==='collection'?btn('Remove reference','remove-collection',ref):''}</p>`;continue;}const page=effectivePage(await getPage(ref.pageId),edits()),section=page.sections.find(s=>s.id===ref.sectionId);if(section)body+=`<article>${btn(`Source: p. ${page.label}`,'page',ref)}${this.mode==='collection'?btn('Move up','move-up',ref)+btn('Move down','move-down',ref)+btn('Remove','remove-collection',ref)+btn(ref.includeHouseRule?'Omit house rule':'Include house rule','include-house',ref):''}${renderSection(page,section,{includeHouseRule:Boolean(ref.includeHouseRule)})}</article>`;}
    if(this.mode==='collection'&&!this.collection.length)body+='<p>Use Collect on sections to assemble a reference article.</p>';
   }else if(!activePage(this.pageId)){body='<p>This page has been removed from the active rulebook. Choose a page from Contents. The GM can restore pages using Manage pages.</p>';}else{
    const page=effectivePage(await getPage(this.pageId),edits()),i=pages.findIndex(p=>p.id===page.id);
    body=`<div class="rb-page-nav">${i?btn('← Previous','page',{pageId:pages[i-1].id}):''}<strong>Book page ${esc(page.label)}</strong>${i<pages.length-1?btn('Next →','page',{pageId:pages[i+1].id}):''}</div><h1>${esc(page.title)}</h1><p class="rb-import-note">${reviewLabel(reviewFor(page).status)}${game.user.isGM?btn('Review status','review-page',{pageId:page.id}):''}</p><div class="rb-actions">${controls(page)}</div>${page.sections.map(s=>renderSection(page,s)).join('')}`;
   }
   return $(`<div class="rb-shell"><aside><h2>Contents</h2><p>${esc(this.book.title)} · ${pages.length} pages</p>${effectiveTOC().map(t=>`<div class="rb-toc-level-${t.level}">${btn(`${this.book.pages.find(p=>p.id===t.pageId)?.label}. ${t.title}`,'page',t)}</div>`).join('')}</aside><main><nav class="rb-tools">${btn('Glossary','glossary')}${btn('Favorites','favorites')}${btn(`Collected (${this.collection.length})`,'collection')}${btn('Back','back')}${game.user.isGM?btn('Manage pages','manage-pages')+btn('Add page','add-page')+btn('Review','review')+btn('Import batch','import-batch')+btn('Export notes','export-notes')+btn('Restore notes','restore-notes'):''}</nav><form data-rb-search><input name="query" value="${esc(this.query)}" placeholder="Search the rulebook" aria-label="Search the rulebook"><button type="submit">Search</button><label><input type="checkbox" name="house" ${this.includeHouseRules?'checked':''}> Include house rules</label></form><div class="rb-content">${body}</div></main></div>`);
  }catch(error){return $(`<div class="rb-error"><h2>Rulebook unavailable</h2><p>${esc(error.message)}</p><p>Add your first page, import a prepared batch, or set Rulebook Content Folder to an existing book folder.</p>${btn('Retry','retry')}${game.user.isGM?btn('Add first page','add-page')+btn('Import batch','import-batch'):''}</div>`);}
 }
 activateListeners(html){super.activateListeners(html);html.on('click','[data-rb]',event=>{event.preventDefault();this.action(event.currentTarget.dataset).catch(error=>ui.notifications.error(error.message));});html.on('click','[data-action="open"]',event=>adapter.openArticle(event.currentTarget.dataset.id));html.on('submit','[data-rb-search]',event=>{event.preventDefault();const data=new FormData(event.currentTarget);this.query=String(data.get('query')||'');this.includeHouseRules=data.has('house');this.mode='search';this.sectionId='';this.render(false);});html.on('input','[data-glossary-filter]',event=>html.find('[data-term]').each((_i,node)=>{node.hidden=!node.dataset.term.includes(event.target.value.toLowerCase());}));if(this.sectionId)html[0].querySelector(`#rb-${CSS.escape(this.sectionId)}`)?.scrollIntoView({block:'start'});}
 async action({rb:action,page:pageId,section:sectionId}){
  const ref={pageId,sectionId};
  if(['manage-pages','add-page','import-batch','export-notes','restore-notes','glossary-edit','add-section','review-page','review'].includes(action)&&!game.user.isGM)throw new Error('Only the GM may manage rulebook content.');
  if(action==='manage-pages')return managePages();
  if(action==='add-page')return addManualPage();
  if(action==='import-batch')return importBatchFile();
  if(action==='export-notes')return exportNotes();if(action==='restore-notes')return restoreNotes();if(action==='glossary-edit')return editGlossary();if(action==='add-section')return addSection(await getPage(pageId));
  if(action==='review-page')return reviewPage(effectivePage(await getPage(pageId),edits()));
  if(action==='complete-rule'){this.ruleRefs=continuationChain(effectiveTOC(),ref).map(r=>({pageId:r.pageId,sectionId:r.sectionId}));this.mode='rule';this.sectionId='';return this.render(false);}
  if(action==='new-collection'){this.collection=[];this.collectionArticle=null;this.mode='collection';return this.render(false);}
  if(action==='move-up'||action==='move-down'){this.collection=moveReference(this.collection,refKey(ref),action==='move-up'?-1:1);return this.render(false);}
  if(action==='retry'){this.book=null;this.index=null;cache.clear();return this.render(false);}
  if(['glossary','favorites','collection','review'].includes(action)){this.mode=action;this.sectionId='';return this.render(false);}
  if(action==='back'){const last=this.history.pop();if(last){this.pageId=last.pageId;this.sectionId=last.sectionId;this.mode='page';}return this.render(false);}
  if(action==='page'){this.history.push({pageId:this.pageId,sectionId:this.sectionId});this.history=this.history.slice(-30);this.pageId=pageId;this.sectionId=sectionId;this.mode='page';return this.render(false);}
  if(action==='remove-collection'){this.collection=this.collection.filter(r=>refKey(r)!==refKey(ref));return this.render(false);}
  if(action==='include-house'){const item=this.collection.find(r=>refKey(r)===refKey(ref));if(item)item.includeHouseRule=!item.includeHouseRule;return this.render(false);}
  if(action==='save-collection'){
   if(!game.user.isGM)throw new Error('Only the GM may create wiki articles.');if(!this.collection.length)throw new Error('Collect at least one section first.');
   const data=await form('Save collected rules',`<label>Article title<input name="title" required value="${esc(this.collectionArticle?.title||'')}"></label><label>Introduction<textarea name="text">${esc(this.collectionArticle?.text||'')}</textarea></label>`);if(!data)return;
   this.collectionArticle=await adapter.saveCollection({id:this.collectionArticle?.id,title:String(data.get('title')),text:String(data.get('text')),bookId:this.book.id,refs:structuredClone(this.collection)});ui.notifications.info('Collected rules saved to the wiki.');return;
  }
  if(!activePage(pageId))throw new Error('This page has been removed from the active rulebook.');
  const page=effectivePage(await getPage(pageId),edits()),section=page.sections.find(s=>s.id===sectionId);
  if(sectionId&&!section)throw new Error('Section not found.');
  if(action==='favorite'){const all=foundry.utils.deepClone(game.user.getFlag(M,'rulebookFavorites')||{}),list=all[this.book.id]||[],exists=list.some(r=>refKey(r)===refKey(ref));all[this.book.id]=exists?list.filter(r=>refKey(r)!==refKey(ref)):[...list,{...ref,label:`${section?.title||page.title} · p. ${page.label}`}];await game.user.setFlag(M,'rulebookFavorites',all);return this.render(false);}
  if(action==='collect'){for(const s of section?[section]:page.sections){const value={pageId,sectionId:s.id};if(!this.collection.some(r=>refKey(r)===refKey(value)))this.collection.push(value);}ui.notifications.info('Added to collected rules.');return this.render(false);}
  if(!game.user.isGM)throw new Error('Only the GM may change or share rules.');
  if(action==='show'){await game.user.setFlag(M,'rulebookShow',{...ref,wholeRule:Boolean(sectionId&&continuationChain(effectiveTOC(),ref).length>1),bookId:this.book.id,nonce:foundry.utils.randomID()});ui.notifications.info('Shown to connected players.');return;}
  if(action==='edit'){const earlier=new Set(this.book.pages.slice(0,this.book.pages.findIndex(p=>p.id===pageId)).map(p=>p.id)),options=effectiveTOC().filter(r=>earlier.has(r.pageId));const data=await form('Edit rulebook section',`<label>Heading<input name="title" value="${esc(section.title)}"></label><label>Continues from<select name="continues"><option value="">A new section</option>${options.map(r=>`<option value="${esc(refKey(r))}" ${section.continuesFrom&&refKey(section.continuesFrom)===refKey(r)?'selected':''}>Page ${esc(this.book.pages.find(p=>p.id===r.pageId).label)} — ${esc(r.title)}</option>`).join('')}</select></label><label>Text<textarea name="text" rows="18">${esc(section.text)}</textarea></label>`);if(data){const previous=options.find(r=>refKey(r)===data.get('continues'));if(previous&&effectiveTOC().some(r=>r.sectionId!==sectionId&&r.continuesFrom&&refKey(r.continuesFrom)===refKey(previous)))throw new Error('That section already continues elsewhere.');await saveEdit(sectionId,{title:String(data.get('title')),text:String(data.get('text')),continuesFrom:previous?{pageId:previous.pageId,sectionId:previous.sectionId}:null});}}
  if(action==='house'){const data=await form('House rule',`<p>This appears only here. Leave blank to remove it.</p><textarea name="text" rows="10">${esc(section.houseRule||'')}</textarea>`);if(data)await saveEdit(sectionId,{houseRule:String(data.get('text')).trim()});}
  if(action==='images'){
   const rows=section.images||[];const data=await form('Section images',`<p>Images belong to this section. Choose an existing image or paste its Forge URL. Clear a path to remove it.</p>${[...rows,{},{}].map((im,i)=>`<fieldset><label>Image ${i+1}<input name="src${i}" value="${esc(im.src||'')}"></label><button type="button" data-rb-file="src${i}">Browse images</button><label>Caption<input name="caption${i}" value="${esc(im.caption||'')}"></label><select name="position${i}"><option value="after">After text</option><option value="before" ${im.position==='before'?'selected':''}>Before text</option></select><details><summary>Searchable image text (optional OCR)</summary><textarea name="imageText${i}" rows="6">${esc(im.searchText||'')}</textarea></details></fieldset>`).join('')}`);
   if(data){const images=[];for(let i=0;i<rows.length+2;i++){const raw=String(data.get(`src${i}`)||'').trim();if(!raw)continue;const src=safeImagePath(raw);if(!src)throw new Error('Use an image file path or HTTPS URL.');images.push({id:rows[i]?.id||foundry.utils.randomID(),src:new URL(src,window.location.href).href,caption:String(data.get(`caption${i}`)||''),position:String(data.get(`position${i}`)),...(String(data.get(`imageText${i}`)||'').trim()?{searchText:String(data.get(`imageText${i}`)).trim()}:{})});}await saveEdit(sectionId,{images});}
  }
  this.render(false);
 }
}
export async function openRulebook(ref={}){reader??=new RulebookReader();try{reader.book??=validateBook(await json('book.json'));}catch(error){if(ref.bookId)throw error;reader.render(true);return;}if(ref.bookId&&ref.bookId!==reader.book.id)throw new Error('This reference belongs to a different rulebook.');if(ref.wholeRule){reader.ruleRefs=continuationChain(effectiveTOC(),ref).map(r=>({pageId:r.pageId,sectionId:r.sectionId}));reader.mode='rule';reader.sectionId='';}else if(ref.refs){reader.collectionArticle=ref.article||null;reader.collection=structuredClone(ref.refs);reader.mode='collection';}else {reader.mode='page';if(ref.pageId)reader.pageId=ref.pageId;reader.sectionId=ref.sectionId||'';}reader.render(true);}
export function installRulebook(options){adapter=options;for(const key of ['rulebookReviews','rulebookGlossary','rulebookRemovedPages'])game.settings.register(M,key,{scope:'world',config:false,type:Object,default:{},onChange:()=>reader?.render(false)});game.settings.register(M,'rulebookPreviousBase',{scope:'world',config:false,type:String,default:''});game.settings.register(M,'rulebookUploadFolder',{name:'Rulebook Upload Folder',hint:'Optional existing data/Forge asset folder. Leave blank to save new revisions in your Assets Library root.',scope:'world',config:true,type:String,default:''});game.settings.register(M,'rulebookBase',{name:'Rulebook Content Folder',hint:'Folder containing book.json; local data module or Forge asset folder URL.',scope:'world',config:true,type:String,default:'modules/hero-rulebook-data',onChange:()=>{cache.clear();if(reader){reader.book=null;reader.index=null;if(!reader.importing)reader.render(false);}}});game.settings.register(M,'rulebookEdits',{scope:'world',config:false,type:Object,default:{},onChange:()=>reader?.render(false)});
 Hooks.on('updateUser',(_user,changes,_options,initiatorId)=>{const ref=changes.flags?.[M]?.rulebookShow;if(ref&&!game.user.isGM&&game.users.get(initiatorId)?.isGM)openRulebook(ref).catch(error=>ui.notifications.warn(error.message));});
}
export async function renderCollectedRules(article,{player=!game.user.isGM}={}){if(!article.rulebookCollection)return '';reader??=new RulebookReader();reader.book??=validateBook(await json('book.json'));const collection=article.rulebookCollection;if(collection.bookId!==reader.book.id)return '<p>Referenced rulebook is unavailable.</p>';let html=`<div class="rb-collected"><h2>Collected rules</h2>${game.user.isGM&&!player?`<button type="button" data-action="edit-rulebook-collection" data-id="${esc(article.id)}">Edit collected rules</button>`:''}`;for(const ref of collection.refs){if(!activePage(ref.pageId)){html+='<p class="rb-import-note">Source page removed or unavailable.</p>';continue;}const page=effectivePage(await getPage(ref.pageId),edits()),section=page.sections.find(s=>s.id===ref.sectionId);if(!section){html+=`<p class="rb-import-note">Source section unavailable: ${esc(ref.sectionId)} (page ${esc(page.label)}).</p>`;continue;}if(section)html+=`<p><button type="button" data-action="rulebook-ref" data-page="${esc(page.id)}" data-section="${esc(section.id)}" data-book="${esc(reader.book.id)}">Rules Book p. ${esc(page.label)} · ${esc(section.title)}</button></p>`+sectionHtml({...section,houseRule:ref.includeHouseRule?section.houseRule:''},{linkText:text=>adapter.linkText(text,player),imageURL});}return html+'</div>';}


