export const UNIFIED_SCHEMA_VERSION=3;
export const ROOTS=Object.freeze([
  {id:"root:metaplots",name:"Metaplots"},{id:"root:arcs",name:"Arcs"},{id:"root:places",name:"Places"},{id:"root:people",name:"People"},{id:"root:images",name:"Images"}
]);
export const ROOT_IDS=new Set(ROOTS.map(root=>root.id));
export const VISIBILITY=Object.freeze({AUTOMATIC:"automatic",PUBLIC:"always-public",GM:"always-gm"});
const clone=value=>globalThis.structuredClone?structuredClone(value):JSON.parse(JSON.stringify(value));
const clean=value=>String(value??"").trim();
const unique=value=>[...new Set((Array.isArray(value)?value:[]).filter(Boolean))];
export const makeArticleId=()=>`article-${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`}`;
export const emptyUnifiedDatabase=(worldId="")=>({schemaVersion:UNIFIED_SCHEMA_VERSION,worldId:clean(worldId),createdAt:new Date().toISOString(),articles:{},resolutions:{},migration:null});
export const rootsById=()=>new Map(ROOTS.map(root=>[root.id,root]));

export function normalizeArticle(input,now=new Date().toISOString()){
  const article=clone(input??{});article.id=clean(article.id)||makeArticleId();article.title=clean(article.title||article.name);article.parentIds=unique(article.parentIds);article.text=String(article.text??article.description??"");article.image=clean(article.image||article.art);article.aliases=unique(article.aliases).map(clean).filter(Boolean).filter(alias=>alias.toLocaleLowerCase()!==article.title.toLocaleLowerCase());article.visibility=Object.values(VISIBILITY).includes(article.visibility)?article.visibility:VISIBILITY.AUTOMATIC;article.date=/^\d{4}-\d{2}-\d{2}$/.test(clean(article.date))?clean(article.date):"";article.status=["in-progress","complete"].includes(article.status)?article.status:"";article.placeholder=Boolean(article.placeholder);article.organizer=Boolean(article.organizer);article.source=article.source?{documentType:clean(article.source.documentType),uuid:clean(article.source.uuid),id:clean(article.source.id),missing:Boolean(article.source.missing)}:null;article.tokenImage=clean(article.tokenImage);article.artworkIssue=article.artworkIssue?{path:clean(article.artworkIssue.path),expectedPath:clean(article.artworkIssue.expectedPath),reason:clean(article.artworkIssue.reason)||"Artwork could not be located."}:null;article.createdAt=article.createdAt||now;article.updatedAt=now;return article;
}
export const articles=(database)=>Object.values(database.articles);
export const childrenOf=(database,parentId)=>articles(database).filter(article=>article.parentIds.includes(parentId));
export const rootName=id=>ROOTS.find(root=>root.id===id)?.name??"";

export function ancestorsOf(database,articleId){const output=new Set(),visiting=new Set();const visit=id=>{if(ROOT_IDS.has(id)||visiting.has(id))return;visiting.add(id);const article=database.articles[id];if(article)for(const parentId of article.parentIds){if(!ROOT_IDS.has(parentId))output.add(parentId);visit(parentId);}visiting.delete(id);};visit(articleId);return [...output];}
export function descendantsOf(database,articleId){const output=new Set();const visit=id=>{for(const child of childrenOf(database,id))if(!output.has(child.id)){output.add(child.id);visit(child.id);}};visit(articleId);return [...output];}
export function wouldCreateCycle(database,articleId,parentId){return parentId===articleId||descendantsOf(database,articleId).includes(parentId);}

export function putArticle(database,input,{preserveRename=true}={}){const previous=input?.id?database.articles[input.id]:null,next=normalizeArticle({...previous,...input,aliases:input.aliases??previous?.aliases??[]});if(!next.title)throw new Error("Article Title is required.");if(!next.parentIds.length)throw new Error("Every Article requires at least one parent.");for(const parentId of next.parentIds){if(!ROOT_IDS.has(parentId)&&!database.articles[parentId])throw new Error(`Unknown parent: ${parentId}`);if(wouldCreateCycle(database,next.id,parentId))throw new Error("An Article cannot be its own ancestor.");}if(preserveRename&&previous?.title&&previous.title!==next.title)next.aliases=unique([...next.aliases,previous.title]);database.articles[next.id]=next;return next;}
export function removeArticle(database,id){if(!database.articles[id])return false;delete database.articles[id];for(const article of articles(database))article.parentIds=article.parentIds.filter(parentId=>parentId!==id);return true;}

export function pathsTo(database,parentId,seen=new Set()){
  if(ROOT_IDS.has(parentId))return[[parentId]];if(seen.has(parentId))return[];const article=database.articles[parentId];if(!article)return[];const next=new Set(seen).add(parentId),paths=[];for(const ancestorId of article.parentIds)for(const path of pathsTo(database,ancestorId,next))paths.push([...path,parentId]);return paths;
}
export function articlePaths(database,article){return article.parentIds.flatMap(parentId=>pathsTo(database,parentId).map(path=>[...path,article.id]));}
export function breadcrumb(database,path){return["Home",...path.map(id=>ROOT_IDS.has(id)?rootName(id):database.articles[id]?.title).filter(Boolean)];}
export function primaryRoot(database,article){return articlePaths(database,article)[0]?.find(id=>ROOT_IDS.has(id))??null;}
export function derivedDateRange(database,articleId){const dates=[articleId,...descendantsOf(database,articleId)].map(id=>database.articles[id]?.date).filter(Boolean).sort();return dates.length?{start:dates[0],end:dates.at(-1)}:null;}

export function isPublic(database,article){if(!article||article.visibility===VISIBILITY.GM)return false;if(article.visibility===VISIBILITY.PUBLIC)return true;const levels=new Map();for(const path of articlePaths(database,article)){for(let index=path.length-2;index>=0;index--){const id=path[index];if(ROOT_IDS.has(id))continue;const distance=path.length-1-index;if(!levels.has(distance))levels.set(distance,new Set());levels.get(distance).add(id);}}for(const distance of [...levels.keys()].sort((a,b)=>a-b)){const ancestors=[...levels.get(distance)].map(id=>database.articles[id]).filter(Boolean);if(ancestors.some(item=>item.visibility===VISIBILITY.GM))return false;if(ancestors.some(item=>item.visibility===VISIBILITY.PUBLIC))return true;}if(article.status==="complete")return true;for(const distance of [...levels.keys()].sort((a,b)=>a-b))if([...levels.get(distance)].some(id=>database.articles[id]?.status==="complete"))return true;return false;}
export function visibleArticles(database,player=false){return articles(database).filter(article=>!player||isPublic(database,article));}

export function needsActioning(database){const items=[];for(const article of articles(database)){if(article.placeholder)items.push({id:`placeholder:${article.id}`,kind:"Incomplete Article",articleId:article.id});if(!article.parentIds.length)items.push({id:`parent:${article.id}`,kind:"Missing Parent",articleId:article.id});if(article.source?.missing)items.push({id:`source:${article.id}`,kind:"Missing Foundry Source",articleId:article.id});if(article.artworkIssue)items.push({id:`artwork:${article.id}`,kind:"Missing Artwork",articleId:article.id});}return items.filter(item=>!database.resolutions[item.id]);}
export function searchArticles(database,query,{player=false}={}){const needle=clean(query).toLocaleLowerCase();if(!needle)return[];return visibleArticles(database,player).flatMap(article=>{if(article.title.toLocaleLowerCase().includes(needle))return[{article,match:"title"}];if(!player){const alias=article.aliases.find(value=>value.toLocaleLowerCase().includes(needle));if(alias)return[{article,match:"alias",alias}];if(article.text.toLocaleLowerCase().includes(needle))return[{article,match:"text"}];}return[];}).sort((a,b)=>a.article.title.localeCompare(b.article.title));}
export function validateUnified(database){const errors=[];if(database.schemaVersion!==UNIFIED_SCHEMA_VERSION)errors.push(`Expected schema ${UNIFIED_SCHEMA_VERSION}.`);for(const article of articles(database)){if(!article.title)errors.push(`${article.id} has no title.`);if(!article.parentIds.length)errors.push(`${article.title} has no parent.`);for(const parentId of article.parentIds)if(!ROOT_IDS.has(parentId)&&!database.articles[parentId])errors.push(`${article.title} has missing parent ${parentId}.`);if(descendantsOf(database,article.id).includes(article.id))errors.push(`${article.title} participates in a cycle.`);}return errors;}

function organizer(database,id,title,parentId){if(database.articles[id])return database.articles[id];return putArticle(database,{id,title,parentIds:[parentId],text:"",image:"",aliases:[],visibility:VISIBILITY.AUTOMATIC,organizer:true});}
export function migrateV2(v2,worldId=""){
  const database=emptyUnifiedDatabase(worldId||v2.worldId),map=new Map(),stats={articles:0,parentLinks:0,needsActioning:0};
  const groups={heroes:organizer(database,"organizer:heroes","Heroes","root:people"),villains:organizer(database,"organizer:villains","Villains","root:people"),npcs:organizer(database,"organizer:npcs","NPCs","root:people"),affiliations:organizer(database,"organizer:affiliations","Affiliations","root:people"),equipment:organizer(database,"organizer:equipment","Equipment","root:images"),macguffins:organizer(database,"organizer:macguffins","MacGuffins","root:images"),media:organizer(database,"organizer:media","Media","root:images"),sessionArt:organizer(database,"organizer:session-art","Session Art","root:images"),vehicles:organizer(database,"organizer:vehicles","Vehicles","root:images"),other:organizer(database,"organizer:other","Other","root:images")};
  for(const old of Object.values(v2.entities??{})){let parents=[];if(old.type==="actor")parents=[groups[old.classification==="hero"?"heroes":old.classification==="villain"?"villains":"npcs"].id];else if(old.type==="scene"||old.type==="area")parents=["root:places"];else if(old.type==="image")parents=[groups[old.classification==="vehicle"?"vehicles":old.classification==="equipment"?"equipment":old.classification==="macguffin"?"macguffins":old.classification==="media"?"media":"other"].id];else if(old.type==="affiliation")parents=[groups.affiliations.id];else if(old.type==="arc")parents=[old.arcType==="metaplot"?"root:metaplots":"root:arcs"];else if(old.type==="session")parents=["root:arcs"];else continue;const source=old.source?{...old.source,documentType:old.type==="actor"?"Actor":"Scene"}:null,missingRequired=Boolean(old.incomplete)||(old.type==="session"&&(!old.synopsis||!old.art))||(old.type==="arc"&&!old.art);const article=putArticle(database,{id:old.id,title:old.name,parentIds:parents,text:old.synopsis??old.description??"",image:old.art||old.portrait||"",tokenImage:old.tokenArt||"",aliases:old.aliases??[],visibility:old.visibility,date:old.playDate||"",status:old.status||"",placeholder:missingRequired,source,legacy:{type:old.type}});map.set(old.id,article.id);stats.articles++;}
  const addParent=(childId,parentId)=>{const child=database.articles[childId];if(child&&parentId&&(ROOT_IDS.has(parentId)||database.articles[parentId])&&!child.parentIds.includes(parentId)){child.parentIds.push(parentId);stats.parentLinks++;}};
  for(const old of Object.values(v2.entities??{})){const id=map.get(old.id),article=database.articles[id];if(!article)continue;if(old.type==="session"&&map.has(old.arcId)){article.parentIds=article.parentIds.filter(value=>value!=="root:arcs");addParent(id,map.get(old.arcId));}if(old.type==="arc"&&old.metaplotId&&map.has(old.metaplotId)){article.parentIds=article.parentIds.filter(value=>value!=="root:arcs");addParent(id,map.get(old.metaplotId));}if(old.type==="area"&&old.parentAreaId&&map.has(old.parentAreaId)){article.parentIds=article.parentIds.filter(value=>value!=="root:places");addParent(id,map.get(old.parentAreaId));}if(old.type==="scene"&&old.areaId&&map.has(old.areaId)){article.parentIds=article.parentIds.filter(value=>value!=="root:places");addParent(id,map.get(old.areaId));}if(old.type==="actor"&&old.dnpcOwnerId&&map.has(old.dnpcOwnerId)){article.parentIds=article.parentIds.filter(value=>value!==groups.npcs.id);addParent(id,map.get(old.dnpcOwnerId));}for(const affiliationId of old.affiliationIds??[])addParent(id,map.get(affiliationId));if(old.type==="session")for(const memberId of old.memberIds??[])addParent(map.get(memberId),id);}
  stats.needsActioning=needsActioning(database).length;database.migration={sourceSchema:v2.schemaVersion??2,migratedAt:new Date().toISOString(),stats};return{database,stats};
}
